/// <summary>
/// Central help provider for all Job Queue and Playbook Workflow message types.
/// Returns Markdown documentation as text; message type implementations pass the
/// result to <c>Message Argument ori.SetResponseMarkdown</c>.
/// </summary>
namespace Origo.Bifrost.Orchestrator;

codeunit 10035576 "Help ori"
{
    Access = Internal;

    /// <summary>
    /// Returns the AI-friendly overview of every Job Queue and Playbook Workflow message type,
    /// including the setup guide for building and scheduling playbooks via Data.Records.Set/Get.
    /// </summary>
    /// <returns>Markdown-formatted overview document as Text.</returns>
    procedure GetOverview() OverviewText: Text
    var
        O: TextBuilder;
    begin
        BuildOverview(O);
        exit(O.ToText());
    end;

    /// <summary>
    /// Returns the per-type help document for a single message type.
    /// </summary>
    /// <param name="MessageType">The message type name (e.g. 'Orchestrator.Playbook.Run').</param>
    /// <returns>Markdown-formatted help document as Text.</returns>
    procedure GetHelp(MessageType: Text) HelpText: Text
    var
        Help: TextBuilder;
    begin
        Help.AppendLine(StrSubstNo(HelpHeadingLbl, MessageType));
        Help.AppendLine('');
        Help.AppendLine('## Overview');
        Help.AppendLine('');
        case MessageType of
            'Orchestrator.Playbook.Run',
            'Orchestrator.Playbook.Schedule',
            'Orchestrator.Playbook.Enqueue':
                BuildPlaybookHelp(Help, MessageType);
            'Orchestrator.JobQueueEntry.Restart',
            'Orchestrator.JobQueueEntry.RestartIfNeeded':
                BuildEntryHelp(Help, MessageType);
            'Orchestrator.Entry.Run',
            'Orchestrator.Entry.Restart',
            'Orchestrator.Entry.Register',
            'Orchestrator.Entry.Schedule':
                BuildSEHelp(Help, MessageType);
            'Orchestrator.Status.Get',
            'Orchestrator.Status.Restart',
            'Orchestrator.Status.RestartIfNeeded':
                BuildStatusHelp(Help, MessageType);
            'Orchestrator.Email.Send':
                BuildEmailSendHelp(Help);
            'Orchestrator.Telegram.Message':
                BuildTelegramHelp(Help);
            'Orchestrator.Report.List',
            'Orchestrator.Report.Get',
            'Orchestrator.Report.SaveAs',
            'Orchestrator.Report.Run':
                BuildReportHelp(Help, MessageType);
            'Orchestrator.Workspace.Preview':
                BuildWorkspacePreviewHelp(Help);
        end;
        exit(Help.ToText());
    end;

    local procedure BuildPlaybookHelp(var Help: TextBuilder; MessageType: Text)
    begin
        case MessageType of
            'Orchestrator.Playbook.Run':
                begin
                    Help.AppendLine('Executes a Bifrost Playbook immediately and returns the execution result. Optionally pass an initial request payload.');
                    Help.AppendLine('');
                    Help.AppendLine('**Direction**: Outbound');
                    Help.AppendLine('');
                    Help.AppendLine('## Request');
                    Help.AppendLine('');
                    Help.AppendLine('| Parameter | Type | Required | Description |');
                    Help.AppendLine('|---|---|---|---|');
                    Help.AppendLine('| `playbookCode` | Code[20] | Yes* | The playbook code to execute |');
                    Help.AppendLine('| `subject` | Text | Yes* | Alternative: pass playbookCode as envelope subject |');
                    Help.AppendLine('| `initialRequest` | Object | No | JSON payload passed to step 1 |');
                    Help.AppendLine('');
                    Help.AppendLine('## Response');
                    Help.AppendLine('');
                    Help.AppendLine('```json');
                    Help.AppendLine('{ "status": "Success", "instanceId": "<guid>", "playbookCode": "MYPLAYBOOK",');
                    Help.AppendLine('  "playbookStatus": "Completed", "stepsExecuted": 3, "stepsFailed": 0, "itemsProcessed": 10 }');
                    Help.AppendLine('```');
                    Help.AppendLine('');
                    Help.AppendLine('## Runs inline, for as long as it takes');
                    Help.AppendLine('');
                    Help.AppendLine('The whole playbook executes inside this call and the response is written only at');
                    Help.AppendLine('the end. A caller that times out first gets nothing, while the server carries on:');
                    Help.AppendLine('the instance is left at `Running` and never completes, because the code that would');
                    Help.AppendLine('write the completion belongs to the session that was abandoned.');
                    Help.AppendLine('');
                    Help.AppendLine('An LLM step inside a forEach is the usual cause — a per-item call against a slow');
                    Help.AppendLine('model turns a twelve-second playbook into several minutes. Use');
                    Help.AppendLine('`Orchestrator.Playbook.Enqueue`, or invoke this type asynchronously, for anything');
                    Help.AppendLine('that is not reliably quick, and read `Playbook Step Log ori` to follow progress.');
                    Help.AppendLine('');
                    Help.AppendLine('`itemsProcessed` counts forEach iterations summed over every step, not distinct');
                    Help.AppendLine('items. Do not present it to a user as a record count.');
                end;
            'Orchestrator.Playbook.Schedule':
                begin
                    Help.AppendLine('Creates an Orchestrator Entry for the playbook using a recurring template. The Orchestrator Handler picks it up automatically and creates the Job Queue Entry.');
                    Help.AppendLine('');
                    Help.AppendLine('**Direction**: Outbound');
                    Help.AppendLine('');
                    Help.AppendLine('## Request');
                    Help.AppendLine('');
                    Help.AppendLine('| Parameter | Type | Required | Description |');
                    Help.AppendLine('|---|---|---|---|');
                    Help.AppendLine('| `playbookCode` | Code[20] | Yes* | The playbook code to schedule |');
                    Help.AppendLine('| `subject` | Text | Yes* | Alternative: pass playbookCode as envelope subject |');
                    Help.AppendLine('| `recurringTemplateCode` | Code[20] | Yes | Recurring template that defines the schedule |');
                    Help.AppendLine('| `notificationType` | Text | No | None, EMail, or Telegram (default: None) |');
                    Help.AppendLine('| `notificationRecipient` | Text | No | Recipient address (required when notificationType is not None) |');
                    Help.AppendLine('| `jobQueueCategoryCode` | Code[10] | No | Job Queue Category Code |');
                    Help.AppendLine('| `emitTelemetry` | Boolean | No | Emit telemetry (default: false) |');
                    Help.AppendLine('| `retryPolicy` | Text | No | Never, ThreeTimes, or Always (default: Always) |');
                    Help.AppendLine('');
                    Help.AppendLine('## Response');
                    Help.AppendLine('');
                    Help.AppendLine('```json');
                    Help.AppendLine('{ "status": "Success", "playbookCode": "MYPLAYBOOK", "scheduled": true, "orchestratorEntryId": "<guid>" }');
                    Help.AppendLine('```');
                end;
            'Orchestrator.Playbook.Enqueue':
                begin
                    Help.AppendLine('Enqueues a playbook for one-time execution via the Job Queue with custom request data. The playbook runs once after the specified delay (minimum 60 seconds).');
                    Help.AppendLine('');
                    Help.AppendLine('**Direction**: Outbound');
                    Help.AppendLine('');
                    Help.AppendLine('## Request');
                    Help.AppendLine('');
                    Help.AppendLine('| Parameter | Type | Required | Description |');
                    Help.AppendLine('|---|---|---|---|');
                    Help.AppendLine('| `playbookCode` | Code[20] | Yes* | The playbook code to enqueue |');
                    Help.AppendLine('| `subject` | Text | Yes* | Alternative: pass playbookCode as envelope subject |');
                    Help.AppendLine('| `initialRequest` | Object | No | JSON payload for step 1 (stored in JQ Parameter table) |');
                    Help.AppendLine('| `jobQueueCategory` | Code[10] | No | Job Queue Category Code for the entry |');
                    Help.AppendLine('| `delaySeconds` | Integer | No | Seconds before execution starts (default/minimum: 60) |');
                    Help.AppendLine('');
                    Help.AppendLine('## Response');
                    Help.AppendLine('');
                    Help.AppendLine('```json');
                    Help.AppendLine('{ "status": "Success", "playbookCode": "MYPLAYBOOK",');
                    Help.AppendLine('  "jobQueueEntryId": "<guid>", "delaySeconds": 60 }');
                    Help.AppendLine('```');
                end;
        end;
    end;

    local procedure BuildEntryHelp(var Help: TextBuilder; MessageType: Text)
    begin
        case MessageType of
            'Orchestrator.JobQueueEntry.Restart':
                Help.AppendLine('Restarts a Job Queue Entry by setting its status to Ready, regardless of current state.');
            'Orchestrator.JobQueueEntry.RestartIfNeeded':
                Help.AppendLine('Restarts a Job Queue Entry only if it is in Error, On Hold, or On Hold with Inactivity Timeout. Returns without action if already Ready or In Process.');
        end;
        Help.AppendLine('');
        Help.AppendLine('**Direction**: Outbound');
        Help.AppendLine('');
        Help.AppendLine('## Request');
        Help.AppendLine('');
        Help.AppendLine('| Parameter | Type | Required | Description |');
        Help.AppendLine('|---|---|---|---|');
        Help.AppendLine('| `id` | GUID | Yes* | SystemId of the Job Queue Entry |');
        Help.AppendLine('| `subject` | GUID | Yes* | Alternative: pass the SystemId as the envelope subject |');
        Help.AppendLine('');
        Help.AppendLine('## Response');
        Help.AppendLine('');
        Help.AppendLine('```json');
        Help.AppendLine('{ "status": "Success", "id": "<guid>", "entryStatus": "Ready", "description": "...", "message": "..." }');
        Help.AppendLine('```');
        Help.AppendLine('');
        Help.AppendLine('## Example');
        Help.AppendLine('');
        Help.AppendLine('```json');
        Help.AppendLine(StrSubstNo(HelpDataIdExampleLbl, MessageType));
        Help.AppendLine('```');
    end;

    local procedure BuildSEHelp(var Help: TextBuilder; MessageType: Text)
    begin
        case MessageType of
            'Orchestrator.Entry.Run':
                Help.AppendLine('Executes an orchestrator entry immediately as a one-time foreground run. Creates a temporary Job Queue Entry copy without affecting the recurring schedule.');
            'Orchestrator.Entry.Restart':
                Help.AppendLine('Restarts a failed or held orchestrator entry by re-enqueuing it. Honors the retry policy and sends restart notifications if configured.');
            'Orchestrator.Entry.Register':
                begin
                    Help.AppendLine('Registers an existing Job Queue Entry as an orchestrator entry. The orchestrator will then manage scheduling, monitoring, and notifications for it.');
                    Help.AppendLine('');
                    Help.AppendLine('**Direction**: Outbound');
                    Help.AppendLine('');
                    Help.AppendLine('## Request');
                    Help.AppendLine('');
                    Help.AppendLine('| Parameter | Type | Required | Description |');
                    Help.AppendLine('|---|---|---|---|');
                    Help.AppendLine('| `jobQueueEntryId` | GUID | Yes* | The ID (PK) of the Job Queue Entry to register |');
                    Help.AppendLine('| `subject` | GUID | Yes* | Alternative: pass the Job Queue Entry ID as the envelope subject |');
                    Help.AppendLine('');
                    Help.AppendLine('## Response');
                    Help.AppendLine('');
                    Help.AppendLine('```json');
                    Help.AppendLine('{ "status": "Success", "id": "<systemId>", "blocked": true, "message": "..." }');
                    Help.AppendLine('```');
                    Help.AppendLine('');
                    Help.AppendLine('## Example');
                    Help.AppendLine('');
                    Help.AppendLine('```json');
                    Help.AppendLine('{ "type": "Orchestrator.Entry.Register", "data": { "jobQueueEntryId": "a1b2c3d4-..." } }');
                    Help.AppendLine('```');
                    exit;
                end;
            'Orchestrator.Entry.Schedule':
                Help.AppendLine('Deletes and immediately recreates the Job Queue Entry for the orchestrator entry. Uses API credentials if configured, otherwise falls back to direct scheduling. Entry must not be blocked.');
        end;
        Help.AppendLine('');
        Help.AppendLine('**Direction**: Outbound');
        Help.AppendLine('');
        Help.AppendLine('## Request');
        Help.AppendLine('');
        Help.AppendLine('| Parameter | Type | Required | Description |');
        Help.AppendLine('|---|---|---|---|');
        Help.AppendLine('| `id` | GUID | Yes* | SystemId of the orchestrator entry |');
        Help.AppendLine('| `subject` | GUID | Yes* | Alternative: pass the SystemId as the envelope subject |');
        Help.AppendLine('');
        Help.AppendLine('*Provide either `id` in the data payload or the SystemId as the `subject`.');
        Help.AppendLine('');
        Help.AppendLine('## Response');
        Help.AppendLine('');
        Help.AppendLine('```json');
        Help.AppendLine('{ "status": "Success", "id": "<guid>", "blocked": true, "message": "..." }');
        Help.AppendLine('```');
        Help.AppendLine('');
        Help.AppendLine('## Example');
        Help.AppendLine('');
        Help.AppendLine('```json');
        Help.AppendLine(StrSubstNo(HelpDataIdExampleLbl, MessageType));
        Help.AppendLine('```');
    end;

    local procedure BuildStatusHelp(var Help: TextBuilder; MessageType: Text)
    begin
        case MessageType of
            'Orchestrator.Status.Get':
                begin
                    Help.AppendLine('Returns the current health status of the Job Queue Orchestrator, including whether the management entry is running and counts of orchestrator entries by state.');
                    Help.AppendLine('');
                    Help.AppendLine('**Direction**: Outbound');
                    Help.AppendLine('');
                    Help.AppendLine('## Request');
                    Help.AppendLine('');
                    Help.AppendLine('No parameters required.');
                    Help.AppendLine('');
                    Help.AppendLine('## Response');
                    Help.AppendLine('');
                    Help.AppendLine('```json');
                    Help.AppendLine('{');
                    Help.AppendLine('  "status": "Success",');
                    Help.AppendLine('  "orchestratorStatus": "Ready",');
                    Help.AppendLine('  "jobQueueCategoryCode": "JOBSSCHDLR",');
                    Help.AppendLine('  "logJobQueueActivity": true,');
                    Help.AppendLine('  "entries": { "total": 10, "blocked": 1, "active": 9 }');
                    Help.AppendLine('}');
                    Help.AppendLine('```');
                end;
            'Orchestrator.Status.Restart':
                begin
                    Help.AppendLine('Unconditionally restarts the orchestrator management Job Queue Entry. Cancels the current entry and creates a new one.');
                    Help.AppendLine('');
                    Help.AppendLine('**Direction**: Outbound');
                    Help.AppendLine('');
                    Help.AppendLine('## Request');
                    Help.AppendLine('');
                    Help.AppendLine('No parameters required.');
                    Help.AppendLine('');
                    Help.AppendLine('## Response');
                    Help.AppendLine('');
                    Help.AppendLine('```json');
                    Help.AppendLine('{ "status": "Success", "message": "Orchestrator restarted.", "orchestratorStatus": "Ready" }');
                    Help.AppendLine('```');
                end;
            'Orchestrator.Status.RestartIfNeeded':
                begin
                    Help.AppendLine('Restarts the orchestrator only if it is not already running. Returns whether a restart was performed.');
                    Help.AppendLine('');
                    Help.AppendLine('**Direction**: Outbound');
                    Help.AppendLine('');
                    Help.AppendLine('## Request');
                    Help.AppendLine('');
                    Help.AppendLine('No parameters required.');
                    Help.AppendLine('');
                    Help.AppendLine('## Response');
                    Help.AppendLine('');
                    Help.AppendLine('```json');
                    Help.AppendLine('{ "status": "Success", "message": "...", "restarted": true }');
                    Help.AppendLine('```');
                end;
        end;
        Help.AppendLine('');
        Help.AppendLine('## Example');
        Help.AppendLine('');
        Help.AppendLine('```json');
        Help.AppendLine(StrSubstNo(HelpTypeOnlyExampleLbl, MessageType));
        Help.AppendLine('```');
    end;

    local procedure BuildOverview(var O: TextBuilder)
    begin
        O.AppendLine('# Job Queue Orchestrator & Playbook Workflow Engine');
        O.AppendLine('');
        O.AppendLine('20 Bifrost message types for managing job queues, building workflow playbooks, and generating reports.');
        O.AppendLine('Call `Help.Implementation.Get` with `subject = "<type>"` for per-type technical guides.');
        O.AppendLine('');
        O.AppendLine('## Quick Decision Tree for AI Agents');
        O.AppendLine('');
        O.AppendLine('**I need to...**');
        O.AppendLine('- Check orchestrator health → `Orchestrator.Status.Get`');
        O.AppendLine('- Restart the orchestrator → `Orchestrator.Status.Restart` or `Orchestrator.Status.RestartIfNeeded`');
        O.AppendLine('- Run an orchestrator entry now → `Orchestrator.Entry.Run`');
        O.AppendLine('- Restart a failed entry → `Orchestrator.Entry.Restart` or `Orchestrator.JobQueueEntry.Restart`');
        O.AppendLine('- Register a JQ entry → `Orchestrator.Entry.Register`');
        O.AppendLine('- Schedule an entry → `Orchestrator.Entry.Schedule`');
        O.AppendLine('- Build a workflow → Create playbook + steps via `Data.Records.Set`, set request templates with `@` workspace references');
        O.AppendLine('- Run a workflow → `Orchestrator.Playbook.Run`');
        O.AppendLine('- Queue a workflow for later → `Orchestrator.Playbook.Enqueue`');
        O.AppendLine('- Send a Telegram message → `Orchestrator.Telegram.Message`');
        O.AppendLine('- List available reports → `Orchestrator.Report.List`');
        O.AppendLine('- Get report details + layouts → `Orchestrator.Report.Get`');
        O.AppendLine('- Generate PDF/Excel/Word report → `Orchestrator.Report.SaveAs`');
        O.AppendLine('- Run a batch job / processing-only report → `Orchestrator.Report.Run`');
        O.AppendLine('- See what workspace variables are available → `Orchestrator.Workspace.Preview`');
        O.AppendLine('');
        O.AppendLine('## Message Types (20)');
        O.AppendLine('');
        O.AppendLine('| Type | Description |');
        O.AppendLine('|---|---|');
        O.AppendLine('| `Orchestrator.Entry.Run` | Execute entry immediately (one-time) |');
        O.AppendLine('| `Orchestrator.Entry.Restart` | Restart a failed/held entry |');
        O.AppendLine('| `Orchestrator.Entry.Register` | Register a Job Queue Entry as an orchestrator entry |');
        O.AppendLine('| `Orchestrator.Entry.Schedule` | Delete + immediately reschedule entry |');
        O.AppendLine('| `Orchestrator.Email.Send` | Send an email (same params as Email.Draft.Set) |');
        O.AppendLine('| `Orchestrator.Status.Get` | Get orchestrator health + entry counts |');
        O.AppendLine('| `Orchestrator.Status.Restart` | Restart orchestrator unconditionally |');
        O.AppendLine('| `Orchestrator.Status.RestartIfNeeded` | Restart only if not running |');
        O.AppendLine('| `Orchestrator.JobQueueEntry.Restart` | Restart any Job Queue Entry |');
        O.AppendLine('| `Orchestrator.JobQueueEntry.RestartIfNeeded` | Restart only if in Error/On Hold |');
        O.AppendLine('| `Orchestrator.Playbook.Run` | Execute playbook, return results |');
        O.AppendLine('| `Orchestrator.Playbook.Schedule` | Schedule playbook as an Orchestrator Entry with recurring template |');
        O.AppendLine('| `Orchestrator.Playbook.Enqueue` | Queue playbook for one-time execution with custom data |');
        O.AppendLine('| `Orchestrator.Telegram.Message` | Send a Telegram message to the current user |');
        O.AppendLine('| `Orchestrator.Report.List` | List available reports with metadata |');
        O.AppendLine('| `Orchestrator.Report.Get` | Get report details, layouts, and saved preset |');
        O.AppendLine('| `Orchestrator.Report.SaveAs` | Generate report output (PDF, Excel, Word, XML) |');
        O.AppendLine('| `Orchestrator.Report.Run` | Run a processing-only report (batch job) |');
        O.AppendLine('| `Orchestrator.Workspace.Preview` | Preview seeded workspace (_sys dates, _who user context) |');
        O.AppendLine('| `Help.Orchestrator.Get` | This help document |');
        O.AppendLine('');
        O.AppendLine('## Run Reporting — `_run` and `_steps`');
        O.AppendLine('');
        O.AppendLine('The runner maintains two reserved top-level workspace keys. Reference them together');
        O.AppendLine('as `@_run,_steps` to hand a language model the whole execution narrative with none of');
        O.AppendLine('the bulk data the steps collected.');
        O.AppendLine('');
        O.AppendLine('`_run` — playbook status:');
        O.AppendLine('```json');
        O.AppendLine('{ "playbookCode": "MONTHEND", "instanceId": "...", "durationMs": 41230,');
        O.AppendLine('  "stepsExecuted": 7, "stepsSucceeded": 5, "stepsFailed": 2, "stepsSkipped": 1,');
        O.AppendLine('  "itemsProcessed": 143, "itemsFailed": 2, "failed": true,');
        O.AppendLine('  "firstFailedStepNo": 30, "failedStepNos": [30, 50] }');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('`_steps.<stepNo>` — one entry per step, accumulating across pages and iterations:');
        O.AppendLine('```json');
        O.AppendLine('{ "stepNo": 30, "description": "Post sales invoices", "messageType": "Sales.Document.Post",');
        O.AppendLine('  "status": "Failed", "durationMs": 1180, "iterated": true, "pages": 1,');
        O.AppendLine('  "items": { "total": 5, "succeeded": 3, "failed": 2, "skipped": 0, "checkFailed": 0 },');
        O.AppendLine('  "failures": [ { "iteration": 2, "outcome": "Failed",');
        O.AppendLine('                  "item": { "no": "103002", "name": "CRONUS Ltd." },');
        O.AppendLine('                  "error": "Posting Date is not within your range." } ],');
        O.AppendLine('  "result": { "postedInvoices": 3, "totalAmount": 45280 } }');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('`_run.itemsProcessed` is the total number of *iterations* across every forEach step,');
        O.AppendLine('not the number of distinct items the playbook handled. Three customers taken through');
        O.AppendLine('four forEach steps count as twelve. When a report needs "how many customers", read');
        O.AppendLine('`_steps.<no>.items.total` for the specific step, and say which step it came from —');
        O.AppendLine('a language model handed `itemsProcessed` will confidently call it a customer count.');
        O.AppendLine('');
        O.AppendLine('`failures` is capped at 20 entries per step (`failuresTruncated` flags the cut), errors');
        O.AppendLine('are truncated to 500 characters, and `item` is a projection of at most 5 scalar fields.');
        O.AppendLine('The counts stay exact regardless. The full request, response and error text remain in');
        O.AppendLine('the step log — filter it by `@_run.instanceId` when the report needs more.');
        O.AppendLine('');
        O.AppendLine('`result` is populated from the step''s `Summary Paths`, which is deliberately separate');
        O.AppendLine('from `Result Log Paths`: the latter feeds later steps and often carries large arrays,');
        O.AppendLine('the former feeds the report and must stay small.');
        O.AppendLine('');
        O.AppendLine('### The reporting tail');
        O.AppendLine('');
        O.AppendLine('A notification tail is four steps: compose and send for success, compose and send for');
        O.AppendLine('failure. Every step carries `Exclude From Run Status`. This is the shape running in');
        O.AppendLine('production, verified on both branches:');
        O.AppendLine('');
        O.AppendLine('```');
        O.AppendLine('Step 900  Start: _run.failed Equals false        [Exclude From Run Status]');
        O.AppendLine('          AND _who.telegramChatId Exists');
        O.AppendLine('          LLM.Prompt.Complete  prompt "@_run,_steps"');
        O.AppendLine('          Result Log Paths: text>noticeText       → next 910 on BOTH edges');
        O.AppendLine('Step 910  Start: 900.noticeText Exists           [Exclude From Run Status]');
        O.AppendLine('          Orchestrator.Telegram.Message  {"message":"@900.noticeText"}');
        O.AppendLine('                                                  → next 920 on BOTH edges');
        O.AppendLine('Step 920  Start: _run.failed Equals true         [Exclude From Run Status]');
        O.AppendLine('          ... same shape, → 930');
        O.AppendLine('Step 930  Start: 920.noticeText Exists           [Exclude From Run Status]');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('Four rules, each of which cost a debugging round to learn:');
        O.AppendLine('');
        O.AppendLine('1. **Point both edges at the next tail step.** A tail step that is skipped, or that');
        O.AppendLine('   fails because a provider was down, must not end the chain — the other branch still');
        O.AppendLine('   has to get its chance. Leaving `Next Step No. (Failure)` at 0 silently drops the');
        O.AppendLine('   failure notification exactly when it is most wanted.');
        O.AppendLine('2. **Guard the send step on the composed text existing**, not on the run outcome. If');
        O.AppendLine('   the compose step was skipped there is nothing to send, and the model occasionally');
        O.AppendLine('   returns an empty completion even when it succeeds.');
        O.AppendLine('3. **Guard on the delivery address too.** `_who.telegramChatId Exists` AND');
        O.AppendLine('   `NotEquals ""` — a user with no chat ID should skip the notice, not fail the run.');
        O.AppendLine('4. **The whole tail is excluded from run status**, so it never narrates itself or');
        O.AppendLine('   inflates the totals the notice is about.');
        O.AppendLine('');
        O.AppendLine('### `_tail` — where excluded steps are recorded');
        O.AppendLine('');
        O.AppendLine('An excluded step is not dropped from the workspace; it is recorded under `_tail.<no>`');
        O.AppendLine('with the same shape as a `_steps` entry. It stays out of `_run` totals and out of the');
        O.AppendLine('`@_run,_steps` dump the report is built from, while remaining referenceable — so one');
        O.AppendLine('tail step can condition on another''s outcome via `_tail.910.status`.');
        O.AppendLine('');
        O.AppendLine('Do not confuse the two namespaces a step writes to:');
        O.AppendLine('');
        O.AppendLine('| Written by | Path | Purpose |');
        O.AppendLine('|---|---|---|');
        O.AppendLine('| `Result Log Paths` | `<stepNo>.<field>` | Data for later steps. Unaffected by exclusion |');
        O.AppendLine('| `Summary Paths` | `_steps.<no>.result` or `_tail.<no>.result` | Figures for the report |');
        O.AppendLine('| the runner | `_steps.<no>` or `_tail.<no>` | Status, duration, errors, item counts |');
        O.AppendLine('');
        O.AppendLine('This is why the send step above references `@900.noticeText` and not');
        O.AppendLine('`@_tail.900.result.noticeText`: `Result Log Paths` writes to the step-number');
        O.AppendLine('namespace whether or not the step is excluded.');
        O.AppendLine('');
        O.AppendLine('## Common Playbook Step Types (from Core Library)');
        O.AppendLine('');
        O.AppendLine('Playbook steps can call **any** registered message type. These are the most commonly used:');
        O.AppendLine('');
        O.AppendLine('| Type | Purpose | Help |');
        O.AppendLine('|---|---|---|');
        O.AppendLine('| `Data.Records.Get` | Read records from any BC table | `Help.Implementation.Get` subject `Data.Records.Get` |');
        O.AppendLine('| `Data.Records.Set` | Write/update records in any BC table | `Help.Implementation.Get` subject `Data.Records.Set` |');
        O.AppendLine('| `LLM.Prompt.Complete` | One-shot AI completion for reasoning, formatting, decisions | `Help.Implementation.Get` subject `LLM.Prompt.Complete` |');
        O.AppendLine('| `Email.Draft.Set` | Create email draft with attachments | `Help.Implementation.Get` subject `Email.Draft.Set` |');
        O.AppendLine('| `Customer.Statement.Pdf` | Generate customer statement PDF | `Help.Implementation.Get` subject `Customer.Statement.Pdf` |');
        O.AppendLine('| `Iceland.Kennitala.Validate` | Validate Icelandic kennitala | `Help.Implementation.Get` subject `Iceland.Kennitala.Validate` |');
        O.AppendLine('| `Iceland.AddressInfo.Get` | Lookup address from national registry | `Help.Implementation.Get` subject `Iceland.AddressInfo.Get` |');
        O.AppendLine('| `DocumentExchange.Advania.*` | E-document exchange (GetUnread, GetDocument, UpdateStatus) | `Help.Implementation.Get` subject `DocumentExchange.Advania.GetUnread` |');
        O.AppendLine('');
        O.AppendLine('**When no standard message type fits** → use `LLM.Prompt.Complete` as the glue step.');
        O.AppendLine('Always call `Help.Implementation.Get` with the message type name before using it in a playbook.');
        O.AppendLine('');
        BuildPlaybookWorkflowGuide(O);
        BuildDataRecordsGuide(O);
        BuildSchedulingGuide(O);
        BuildLLMPatternsGuide(O);
        BuildAgentRules(O);
    end;

    local procedure BuildPlaybookWorkflowGuide(var O: TextBuilder)
    begin
        O.AppendLine('## Playbook Workflow Engine — Concepts');
        O.AppendLine('');
        O.AppendLine('A **Playbook** is a named sequence of message type calls with data flow through a shared **Workspace**.');
        O.AppendLine('');
        O.AppendLine('### Execution Model');
        O.AppendLine('');
        O.AppendLine('- Each step calls one Bifrost message type');
        O.AppendLine('- Steps execute sequentially; each step''s writes commit independently');
        O.AppendLine('- **No rollback** of previous steps on failure');
        O.AppendLine('- Steps branch on success/failure via `Next Step No. (Success)` / `Next Step No. (Failure)`');
        O.AppendLine('- Step 0 as next = end playbook (success or failure depending on path)');
        O.AppendLine('- Full request/response logged per step for audit and replay');
        O.AppendLine('');
        O.AppendLine('### Data Flow — Workspace + @Templates');
        O.AppendLine('');
        O.AppendLine('All data flows through a **single JSON workspace document**. Two phases:');
        O.AppendLine('');
        O.AppendLine('**Phase 1 — Gather:** Steps execute and write results to workspace via `Result Log Paths`.');
        O.AppendLine('Data is keyed by step number (and iteration number for forEach):');
        O.AppendLine('- Single step: `<StepNo>.<fieldName>` (e.g. `10.company`)');
        O.AppendLine('- forEach step: `<StepNo>.<IterationNo>.<fieldName>` (e.g. `20.0.valid`, `20.1.valid`)');
        O.AppendLine('- Initial request: stored at `_initial` (e.g. `_initial.invoiceNo`)');
        O.AppendLine('- Current forEach element: stored at `_current` during each iteration');
        O.AppendLine('- System constants: stored at `_sys` (dates, company, user)');
        O.AppendLine('- WhoAmI context: stored at `_who` (user profile, salesperson, company info)');
        O.AppendLine('');
        O.AppendLine('**Phase 2 — Build:** Request templates use `@path` references resolved from workspace:');
        O.AppendLine('');
        O.AppendLine('| Syntax | Resolves to | Example |');
        O.AppendLine('|---|---|---|');
        O.AppendLine('| `"@path"` | Single value/object/array (type-preserving) | `"@10.company.fields.Name"` → `"CRONUS Ltd."` |');
        O.AppendLine('| `"@_current.field"` | Current forEach element field | `"@_current.fields.No_"` → `"10000"` |');
        O.AppendLine('| `"@_initial.key"` | Initial request parameter | `"@_initial.invoiceNo"` → `"103002"` |');
        O.AppendLine('| `"@_iter"` | Current forEach iteration index | `"@30.@_iter.street"` → resolves to `"@30.0.street"` then to the value |');
        O.AppendLine('| `"@_sys.field"` | System constant | `"@_sys.today"` → `"2026-08-30"`, `"@_sys.lastMonthStart"` → `"2026-07-01"` |');
        O.AppendLine('| `"@_who.path"` | WhoAmI user/company context | `"@_who.salesperson.email"` → `"user@company.is"` |');
        O.AppendLine('| `"@collect:N"` | All iterations of step N as array | `"@collect:25"` → `[{...}, {...}]` |');
        O.AppendLine('| `"@k1,k2,k3"` | Filtered workspace dump (escaped string) | `"@10,20,30"` → `"{\"10\":...}"` |');
        O.AppendLine('| `@path` (embedded) | Text interpolation within a string | `"WHERE(No.=CONST(@_initial.id))"` |');
        O.AppendLine('');
        O.AppendLine('Numeric strings are auto-detected and injected as JSON numbers.');
        O.AppendLine('');
        O.AppendLine('### Result Log Paths');
        O.AppendLine('');
        O.AppendLine('The `Result Log Paths` field controls what data each step writes to workspace.');
        O.AppendLine('Comma-separated, supports `source>target` renaming:');
        O.AppendLine('');
        O.AppendLine('| Syntax | Source in response | Stored at (single step 10) |');
        O.AppendLine('|---|---|---|');
        O.AppendLine('| `result` | `result` | `10.result` |');
        O.AppendLine('| `result>customers` | `result` | `10.customers` |');
        O.AppendLine('| `result[0]>invoice` | First element of `result` | `10.invoice` (no array wrapper) |');
        O.AppendLine('| `result.valid>valid` | `result.valid` | `10.valid` |');
        O.AppendLine('');
        O.AppendLine('### ForEach Iteration');
        O.AppendLine('');
        O.AppendLine('A step with `Iterate Array Path` set becomes a foreach loop:');
        O.AppendLine('- Extracts an array from a prior step''s response (via ResponseStore)');
        O.AppendLine('- Executes the message type once per array element');
        O.AppendLine('- `@_current` in the request template resolves to the current element');
        O.AppendLine('- `Stop On Item Error` controls whether to abort on first failure');
        O.AppendLine('- Each iteration writes to workspace at `<StepNo>.<IterationNo>.<field>`');
        O.AppendLine('- The iterator element is also stored at `<StepNo>.<IterationNo>._item`');
        O.AppendLine('- Use `@collect:N` to gather all iterations into an array');
        O.AppendLine('');
        O.AppendLine('### Conditions');
        O.AppendLine('');
        O.AppendLine('Steps can evaluate the response to determine success/failure:');
        O.AppendLine('Conditions live in `Playbook Condition ori`, keyed by playbook, step, type, group and line.');
        O.AppendLine('');
        O.AppendLine('| Type | Evaluated | Against | Effect |');
        O.AppendLine('|---|---|---|---|');
        O.AppendLine('| `Start` | before the step | workspace | False = step is Cancelled, chain follows the success path |');
        O.AppendLine('| `Success` | after the step | response | Picks the success or failure branch |');
        O.AppendLine('| `Error` | after the step | workspace | True = mark the run failed, branch unchanged |');
        O.AppendLine('');
        O.AppendLine('**All conditions in a group must hold. Any group holding is enough.**');
        O.AppendLine('AND within a `Group No.`, OR across groups — every boolean expression can be');
        O.AppendLine('written that way, so there is no nesting, precedence or parentheses to learn.');
        O.AppendLine('An empty condition set is true.');
        O.AppendLine('');
        O.AppendLine('```');
        O.AppendLine('Type   Group  Path                       Operator   Value');
        O.AppendLine('Start  1      _run.failed                Equals     true');
        O.AppendLine('Start  2      _steps.30.items.succeeded  Equals     0');
        O.AppendLine('Start  2      _steps.30.status           NotEquals  Cancelled');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('Operators: Equals, NotEquals, Contains, GreaterThan, LessThan, GreaterOrEqual, LessOrEqual, Exists.');
        O.AppendLine('');
        O.AppendLine('### `status Equals Success` is not enough');
        O.AppendLine('');
        O.AppendLine('A message type reports `Success` when it did what was asked, and finding nothing is');
        O.AppendLine('doing what was asked. `Data.Records.Get` over a filter that matches no rows returns');
        O.AppendLine('`{"status":"Success","noOfRecords":0,"result":[]}`. A step guarded only on `status`');
        O.AppendLine('accepts that, the forEach below it iterates zero times and also succeeds, and the run');
        O.AppendLine('ends Completed having done nothing — with the real cause several steps upstream.');
        O.AppendLine('');
        O.AppendLine('Add the second condition in the same group, so both must hold:');
        O.AppendLine('');
        O.AppendLine('```');
        O.AppendLine('Type     Group  Line   Path          Operator      Value');
        O.AppendLine('Success  1      10000  status        Equals        Success');
        O.AppendLine('Success  1      20000  noOfRecords   GreaterThan   0');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('Then decide what an empty result *means*. If the playbook has nothing to do when the');
        O.AppendLine('query is empty, that is a `Check` step — it routes down the failure edge to a tidy');
        O.AppendLine('ending without marking the run failed. If an empty result means something upstream is');
        O.AppendLine('broken, leave it an `Action` so the run fails and names this step.');
        O.AppendLine('');
        O.AppendLine('### Step Type — checks are not errors');
        O.AppendLine('');
        O.AppendLine('- `Action` (default): a false Success condition means the step failed, and the run fails.');
        O.AppendLine('- `Check`: a false Success condition is simply the answer. It still routes down the');
        O.AppendLine('  failure path and still drives `Skip If Step Failed`, but it does **not** fail the run.');
        O.AppendLine('');
        O.AppendLine('Use `Check` for validations and predicates — "is this kennitala valid", "did the');
        O.AppendLine('address match", "are there any documents to import". A step asking a question and');
        O.AppendLine('getting "no" has not failed.');
        O.AppendLine('- If no condition set, step succeeds whenever the message type doesn''t throw an error');
        O.AppendLine('');
    end;

    local procedure BuildDataRecordsGuide(var O: TextBuilder)
    begin
        O.AppendLine('## Building Workflows via Data.Records.Set/Get');
        O.AppendLine('');
        O.AppendLine('### Tables');
        O.AppendLine('');
        O.AppendLine('| Table | Purpose | Primary Key |');
        O.AppendLine('|---|---|---|');
        O.AppendLine('| `Playbook ori` | Playbook header (name, schedule, template) | Code[20] |');
        O.AppendLine('| `Playbook Step ori` | Step definition (message type, template, branching) | (PlaybookCode, StepNo_) |');
        O.AppendLine('| `Playbook Condition ori` | Start/Success/Error conditions, one row per condition | (PlaybookCode, StepNo_, ConditionType, GroupNo_, LineNo_) |');
        O.AppendLine('| `Recurring Template ori` | Reusable schedule template (days, time, interval) | Code[20] |');
        O.AppendLine('| `Playbook Instance ori` | Execution log (per run) | ID (Guid) |');
        O.AppendLine('| `Playbook Step Log ori` | Per-step execution detail | (Instance ID, Step No., Iteration No.) |');
        O.AppendLine('');
        O.AppendLine('### Example: E-Document Send Playbook (BII1 invoice via Advania)');
        O.AppendLine('');
        O.AppendLine('**Step 1: Create the playbook**');
        O.AppendLine('```json');
        O.AppendLine('{ "type": "Data.Records.Set", "data": {');
        O.AppendLine('  "tableName": "Playbook ori",');
        O.AppendLine('  "data": [{ "primaryKey": { "Code": "EDOC-SEND" },');
        O.AppendLine('    "fields": { "Description": "Send invoice via Advania" } }]');
        O.AppendLine('} }');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('**Step 2: Add steps with request templates**');
        O.AppendLine('Request templates are BLOB fields — pass base64-encoded JSON:');
        O.AppendLine('```json');
        O.AppendLine('{ "type": "Data.Records.Set", "data": {');
        O.AppendLine('  "tableName": "Playbook Step ori",');
        O.AppendLine('  "data": [');
        O.AppendLine('    { "primaryKey": { "PlaybookCode": "EDOC-SEND", "StepNo_": 10 },');
        O.AppendLine('      "fields": { "Description": "Get company info",');
        O.AppendLine('        "MessageType": "Data.Records.Get",');
        O.AppendLine('        "RequestTemplate": "<base64 of {\"tableName\":\"Company Information\",...}>",');
        O.AppendLine('        "ResultLogPaths": "result[0]>company",');
        O.AppendLine('        "NextStepNo_Success": 20 } },');
        O.AppendLine('    { "primaryKey": { "PlaybookCode": "EDOC-SEND", "StepNo_": 20 },');
        O.AppendLine('      "fields": { "Description": "Render BII1 XML",');
        O.AppendLine('        "MessageType": "DocumentExchange.UBL.RenderBilling",');
        O.AppendLine('        "RequestTemplate": "<base64 of template with @10.company.fields.Name etc>",');
        O.AppendLine('        "ResultLogPaths": "xml,success" } }');
        O.AppendLine('  ] } }');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('**Step 3: Run with parameters**');
        O.AppendLine('```json');
        O.AppendLine('{ "type": "Orchestrator.Playbook.Run", "data": {');
        O.AppendLine('  "playbookCode": "EDOC-SEND",');
        O.AppendLine('  "initialRequest": { "invoiceNo": "103002" } } }');
        O.AppendLine('```');
        O.AppendLine('The `initialRequest` is stored in workspace at `_initial`, accessible as `@_initial.invoiceNo`.');
        O.AppendLine('');
        O.AppendLine('### Writing conditions');
        O.AppendLine('');
        O.AppendLine('Conditions are ordinary records. One row per condition, `Line No.` spaced like step');
        O.AppendLine('numbers so rows can be inserted between:');
        O.AppendLine('');
        O.AppendLine('```json');
        O.AppendLine('{ "type": "Data.Records.Set", "data": {');
        O.AppendLine('  "tableName": "Playbook Condition ori",');
        O.AppendLine('  "data": [');
        O.AppendLine('    { "primaryKey": { "PlaybookCode": "EDOC-SEND", "StepNo_": 10,');
        O.AppendLine('        "ConditionType": "Success", "GroupNo_": 1, "LineNo_": 10000 },');
        O.AppendLine('      "fields": { "Path": "status", "Operator": "Equals", "Value": "Success" } },');
        O.AppendLine('    { "primaryKey": { "PlaybookCode": "EDOC-SEND", "StepNo_": 10,');
        O.AppendLine('        "ConditionType": "Success", "GroupNo_": 1, "LineNo_": 20000 },');
        O.AppendLine('      "fields": { "Path": "noOfRecords", "Operator": "GreaterThan", "Value": "0" } }');
        O.AppendLine('  ] } }');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('**Write enum fields by their AL name, not their caption.** `Operator` accepts');
        O.AppendLine('`NotEquals`, `GreaterOrEqual`, `LessOrEqual`; it rejects `Not Equals`. `ConditionType`');
        O.AppendLine('accepts `Start`, `Success`, `Error`. `Step Type` accepts `Action`, `Check`.');
        O.AppendLine('');
        O.AppendLine('**A `Data.Records.Get` on these tables gives back captions, not names.** An is-IS');
        O.AppendLine('session reads `Operator: "Ekki jafnt"`, `ConditionType: "Upphaf"`. Requesting');
        O.AppendLine('`lcid: 1033` does not fix it: the English caption for `NotEquals` is `Not Equals`,');
        O.AppendLine('with a space, and `Set` rejects that too. Some names and captions coincide —');
        O.AppendLine('`Equals`, `Exists`, `Start` — which makes the failure look intermittent.');
        O.AppendLine('');
        O.AppendLine('So a read-modify-write cycle over conditions cannot feed its own output back in.');
        O.AppendLine('Map captions to AL names yourself, or keep the intended values beside the code that');
        O.AppendLine('writes them rather than recovering them from a Get.');
        O.AppendLine('');
    end;

    local procedure BuildSchedulingGuide(var O: TextBuilder)
    begin
        O.AppendLine('## Scheduling Playbooks for Recurring Execution');
        O.AppendLine('');
        O.AppendLine('Playbooks can run on a recurring schedule via the Job Queue. Two approaches:');
        O.AppendLine('');
        O.AppendLine('### Option A: Use a Recurring Template (recommended)');
        O.AppendLine('');
        O.AppendLine('Templates define reusable schedules (days, time window, interval).');
        O.AppendLine('');
        O.AppendLine('**1. Create or find a template:**');
        O.AppendLine('```json');
        O.AppendLine('{ "type": "Data.Records.Get", "data": { "tableName": "Recurring Template ori" } }');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('**2. Create a template if needed:**');
        O.AppendLine('```json');
        O.AppendLine('{ "type": "Data.Records.Set", "data": {');
        O.AppendLine('  "tableName": "Recurring Template ori",');
        O.AppendLine('  "data": [{ "primaryKey": { "Code": "WORKDAYS" },');
        O.AppendLine('    "fields": { "Description": "Weekdays 08-18 every 30 min",');
        O.AppendLine('      "RunonMondays": true, "RunonTuesdays": true, "RunonWednesdays": true,');
        O.AppendLine('      "RunonThursdays": true, "RunonFridays": true,');
        O.AppendLine('      "RunonSaturdays": false, "RunonSundays": false,');
        O.AppendLine('      "StartingTime": "08:00:00", "EndingTime": "18:00:00",');
        O.AppendLine('      "No_ofMinutesbetweenRuns": 30 } }]');
        O.AppendLine('} }');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('**3. Assign template to playbook (auto-copies schedule fields):**');
        O.AppendLine('```json');
        O.AppendLine('{ "type": "Data.Records.Set", "data": {');
        O.AppendLine('  "tableName": "Playbook ori",');
        O.AppendLine('  "data": [{ "primaryKey": { "Code": "MY-PLAYBOOK" },');
        O.AppendLine('    "fields": { "RecurringTemplateCode": "WORKDAYS" } }]');
        O.AppendLine('} }');
        O.AppendLine('```');
        O.AppendLine('When a template is set, the playbook''s schedule fields (days, times, interval) are');
        O.AppendLine('automatically populated from the template and locked from manual editing.');
        O.AppendLine('');
        O.AppendLine('### Option B: Set schedule directly on the playbook');
        O.AppendLine('');
        O.AppendLine('```json');
        O.AppendLine('{ "type": "Data.Records.Set", "data": {');
        O.AppendLine('  "tableName": "Playbook ori",');
        O.AppendLine('  "data": [{ "primaryKey": { "Code": "MY-PLAYBOOK" },');
        O.AppendLine('    "fields": { "RunonMondays": true, "RunonTuesdays": true,');
        O.AppendLine('      "RunonWednesdays": true, "RunonThursdays": true, "RunonFridays": true,');
        O.AppendLine('      "StartingTime": "06:00:00", "EndingTime": "22:00:00",');
        O.AppendLine('      "No_ofMinutesbetweenRuns": 60 } }]');
        O.AppendLine('} }');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('### Activating the schedule');
        O.AppendLine('');
        O.AppendLine('After setting the schedule, use the **Schedule** action on the Playbook Card page');
        O.AppendLine('to create the Job Queue Entry. This creates a recurring JQ Entry pointing to the');
        O.AppendLine('Bifrost Playbook JQ Dispatcher codeunit with the playbook''s RecordId.');
        O.AppendLine('');
        O.AppendLine('**Key playbook fields for scheduling:**');
        O.AppendLine('');
        O.AppendLine('| Field | Type | Purpose |');
        O.AppendLine('|---|---|---|');
        O.AppendLine('| `RecurringTemplateCode` | Code[20] | Links to JQ Recurring Template (optional) |');
        O.AppendLine('| `No_ofMinutesbetweenRuns` | Integer | Run interval in minutes |');
        O.AppendLine('| `RunonMondays`..`RunonSundays` | Boolean | Which days to run |');
        O.AppendLine('| `StartingTime` | Time | Earliest time of day |');
        O.AppendLine('| `EndingTime` | Time | Latest time of day |');
        O.AppendLine('| `Scheduled` | Boolean (FlowField) | Whether a JQ Entry exists (read-only) |');
        O.AppendLine('| `JobQueueEntryID` | Guid | The created JQ Entry ID (read-only) |');
        O.AppendLine('');
    end;

    local procedure BuildTelegramHelp(var Help: TextBuilder)
    begin
        Help.AppendLine('Sends a Telegram message to the current user. The chat ID is resolved from the calling user''s Bifrost User Setup — no chat ID parameter in the request.');
        Help.AppendLine('');
        Help.AppendLine('**Direction**: Outbound');
        Help.AppendLine('');
        Help.AppendLine('## Prerequisites');
        Help.AppendLine('');
        Help.AppendLine('1. **HTTP Client Requests** enabled for the extension (Extension Settings page 2500)');
        Help.AppendLine('2. **Telegram Bot Token** configured in Orchestrator Setup');
        Help.AppendLine('3. **Telegram Chat ID** set on the calling user''s Bifrost User Setup record');
        Help.AppendLine('');
        Help.AppendLine('## Request');
        Help.AppendLine('');
        Help.AppendLine('| Parameter | Type | Required | Description |');
        Help.AppendLine('|---|---|---|---|');
        Help.AppendLine('| `message` | Text | Yes | The message text to send (supports HTML formatting) |');
        Help.AppendLine('');
        Help.AppendLine('## Response');
        Help.AppendLine('');
        Help.AppendLine('```json');
        Help.AppendLine('{ "status": "Success", "chatId": "123456789" }');
        Help.AppendLine('```');
        Help.AppendLine('');
        Help.AppendLine('## Example');
        Help.AppendLine('');
        Help.AppendLine('```json');
        Help.AppendLine('{ "type": "Orchestrator.Telegram.Message", "data": { "message": "Hello from BC!" } }');
        Help.AppendLine('```');
        Help.AppendLine('');
        Help.AppendLine('## IsEnabled');
        Help.AppendLine('');
        Help.AppendLine('Returns true only when all three prerequisites are met. If `IsEnabled` returns false, the message type will not appear in available type listings for the current user.');
        Help.AppendLine('');
    end;

    local procedure BuildEmailSendHelp(var Help: TextBuilder)
    begin
        Help.AppendLine('Sends an email draft created by Email.Draft.Set. Requires the outboxSystemId from the draft response.');
        Help.AppendLine('');
        Help.AppendLine('**Direction**: Inbound');
        Help.AppendLine('');
        Help.AppendLine('## Request');
        Help.AppendLine('');
        Help.AppendLine('| Parameter | Type | Required | Description |');
        Help.AppendLine('|---|---|---|---|');
        Help.AppendLine('| `outboxSystemId` | GUID | Yes* | SystemId of the Email Outbox entry (from Email.Draft.Set response) |');
        Help.AppendLine('| `subject` | GUID | Yes* | Alternative: pass outboxSystemId as envelope subject |');
        Help.AppendLine('');
        Help.AppendLine('## Response');
        Help.AppendLine('');
        Help.AppendLine('```json');
        Help.AppendLine('{ "status": "Success", "messageId": "<guid>", "outboxSystemId": "<guid>" }');
        Help.AppendLine('```');
        Help.AppendLine('');
        Help.AppendLine('## Playbook Pattern');
        Help.AppendLine('');
        Help.AppendLine('Two-step email flow in a playbook:');
        Help.AppendLine('1. Step N: `Email.Draft.Set` — template: `{"to":"...","subject":"...","htmlBody":"@prev.report"}`');
        Help.AppendLine('   Set `ResultLogPaths = "outboxSystemId"` to capture the draft ID in workspace');
        Help.AppendLine('2. Step N+10: `Orchestrator.Email.Send` — template: `{"outboxSystemId":"@N.outboxSystemId"}`');
        Help.AppendLine('   Uses `@` workspace reference to the draft''s outboxSystemId');
        Help.AppendLine('');
        Help.AppendLine('This separation allows:');
        Help.AppendLine('- Using Email.Draft.Set for review-before-send workflows (skip the Send step)');
        Help.AppendLine('- Reusing Email.Draft.Set''s full feature set (attachments, scenarios, CC/BCC)');
        Help.AppendLine('- Keeping Orchestrator.Email.Send simple and focused');
        Help.AppendLine('');
    end;

    local procedure BuildReportHelp(var Help: TextBuilder; MessageType: Text)
    begin
        case MessageType of
            'Orchestrator.Report.List':
                begin
                    Help.AppendLine('Lists available reports from Report Metadata, excluding obsolete reports.');
                    Help.AppendLine('');
                    Help.AppendLine('**Direction**: Outbound');
                    Help.AppendLine('');
                    Help.AppendLine('## Request');
                    Help.AppendLine('');
                    Help.AppendLine('| Parameter | Type | Required | Description |');
                    Help.AppendLine('|---|---|---|---|');
                    Help.AppendLine('| `processingOnly` | Boolean | No | Filter by processing-only flag |');
                    Help.AppendLine('');
                    Help.AppendLine('## Response');
                    Help.AppendLine('');
                    Help.AppendLine('```json');
                    Help.AppendLine('{ "reports": [{ "id": 206, "name": "Sales - Invoice", "caption": "Sales Invoice",');
                    Help.AppendLine('    "processingOnly": false, "defaultLayout": "RDLC",');
                    Help.AppendLine('    "firstDataItemTableId": 112, "useRequestPage": true }], "count": 1 }');
                    Help.AppendLine('```');
                end;
            'Orchestrator.Report.Get':
                begin
                    Help.AppendLine('Returns full report metadata including layouts and saved request page preset XML.');
                    Help.AppendLine('');
                    Help.AppendLine('**Direction**: Outbound');
                    Help.AppendLine('');
                    Help.AppendLine('## Request');
                    Help.AppendLine('');
                    Help.AppendLine('| Parameter | Type | Required | Description |');
                    Help.AppendLine('|---|---|---|---|');
                    Help.AppendLine('| `reportId` | Integer | Yes | The report object ID |');
                    Help.AppendLine('');
                    Help.AppendLine('## Response');
                    Help.AppendLine('');
                    Help.AppendLine('Includes `layouts` array with available report layouts and `preset` object with');
                    Help.AppendLine('the user''s saved `requestPageXml` (null if no preset exists). Also includes');
                    Help.AppendLine('`requestPageUrl` to open the report in BC for interactive configuration.');
                    Help.AppendLine('');
                    Help.AppendLine('## Preset Capture Flow');
                    Help.AppendLine('');
                    Help.AppendLine('1. Call Report.Get to get `presetCapturePageUrl`');
                    Help.AppendLine('2. Open that URL in BC to capture request page parameters');
                    Help.AppendLine('3. Call Report.Get again — `preset.requestPageXml` is now populated');
                    Help.AppendLine('4. Use in playbooks via Report.SaveAs (auto-resolves from preset)');
                end;
            'Orchestrator.Report.SaveAs':
                begin
                    Help.AppendLine('Generates report output (PDF, Excel, Word, XML). Returns binary content via the standard response blob.');
                    Help.AppendLine('');
                    Help.AppendLine('**Direction**: Outbound');
                    Help.AppendLine('');
                    Help.AppendLine('## Request');
                    Help.AppendLine('');
                    Help.AppendLine('| Parameter | Type | Required | Description |');
                    Help.AppendLine('|---|---|---|---|');
                    Help.AppendLine('| `reportId` | Integer | Yes | The report object ID |');
                    Help.AppendLine('| `format` | Text | No | PDF (default), Excel, Word, XML |');
                    Help.AppendLine('| `requestPageXml` | Text | No | Report parameters XML. Falls back to saved preset, then defaults |');
                    Help.AppendLine('| `tableView` | Text | No | BC table view filter for the root data item |');
                    Help.AppendLine('| `layoutName` | Text | No | Override layout name (from Report.Get layouts) |');
                    Help.AppendLine('');
                    Help.AppendLine('## Response');
                    Help.AppendLine('');
                    Help.AppendLine('Binary content (e.g. PDF) in the response blob. Via MCP: returned as `blobRef`.');
                    Help.AppendLine('');
                    Help.AppendLine('## Playbook Pattern — Batch report to email');
                    Help.AppendLine('');
                    Help.AppendLine('```');
                    Help.AppendLine('Step 10: Data.Records.Get → customer list');
                    Help.AppendLine('Step 20 (forEach): Orchestrator.Report.SaveAs');
                    Help.AppendLine('  { "reportId": 206, "format": "PDF",');
                    Help.AppendLine('    "tableView": "WHERE(Sell-to Customer No.=CONST(@_current.no))" }');
                    Help.AppendLine('Step 30 (forEach): Email.Draft.Set with blobRef attachment');
                    Help.AppendLine('Step 40 (forEach): Orchestrator.Email.Send');
                    Help.AppendLine('```');
                end;
            'Orchestrator.Report.Run':
                begin
                    Help.AppendLine('Runs a processing-only report — a batch job such as Adjust Cost, Post Inventory Cost to G/L,');
                    Help.AppendLine('or Update Currency Exchange Rates. These reports produce no document; they change data.');
                    Help.AppendLine('');
                    Help.AppendLine('**Direction**: Outbound');
                    Help.AppendLine('');
                    Help.AppendLine('## Request');
                    Help.AppendLine('');
                    Help.AppendLine('| Parameter | Type | Required | Description |');
                    Help.AppendLine('|---|---|---|---|');
                    Help.AppendLine('| `reportId` | Integer | Yes | Must be a report with `processingOnly: true` |');
                    Help.AppendLine('| `requestPageXml` | Text | No | Report parameters XML. Falls back to saved preset, then defaults |');
                    Help.AppendLine('| `tableView` | Text | No | BC table view filter for the root data item |');
                    Help.AppendLine('');
                    Help.AppendLine('Reports that produce output are rejected — use `Orchestrator.Report.SaveAs` for those.');
                    Help.AppendLine('');
                    Help.AppendLine('## Response');
                    Help.AppendLine('');
                    Help.AppendLine('```json');
                    Help.AppendLine('{ "status": "Success", "reportId": 795, "reportName": "Adjust Cost - Item Entries",');
                    Help.AppendLine('  "usedPreset": true, "tableView": "", "durationMs": 41230 }');
                    Help.AppendLine('```');
                    Help.AppendLine('');
                    Help.AppendLine('A failing report is caught and returned, not thrown:');
                    Help.AppendLine('');
                    Help.AppendLine('```json');
                    Help.AppendLine('{ "status": "Error", "error": "<BC error text>", "callstack": "<BC error callstack>" }');
                    Help.AppendLine('```');
                    Help.AppendLine('');
                    Help.AppendLine('## Read This Before Using It');
                    Help.AppendLine('');
                    Help.AppendLine('- **Success only means no error was raised.** The report returns no result. A run that');
                    Help.AppendLine('  matched zero records looks identical to one that adjusted 50,000 entries. Verify with a');
                    Help.AppendLine('  following `Data.Records.Get` step against the register or ledger the report writes to.');
                    Help.AppendLine('- **Effects are irreversible, and partial on failure.** Most batch reports commit as they go,');
                    Help.AppendLine('  so `{"status":"Error"}` does NOT mean nothing happened.');
                    Help.AppendLine('- **Do not auto-retry.** Set the orchestrator entry retry policy to `Never` for any chain');
                    Help.AppendLine('  containing this step.');
                    Help.AppendLine('- **Check what you are calling first.** `Orchestrator.Report.List` with');
                    Help.AppendLine('  `{"processingOnly": true}` is unfiltered — it lists Date Compress G/L Entries and Delete');
                    Help.AppendLine('  Invoiced Sales Orders next to the harmless ones. Call `Orchestrator.Report.Get` to confirm');
                    Help.AppendLine('  what a reportId actually is before running it.');
                    Help.AppendLine('- **No request page is shown.** Parameters come only from `requestPageXml` or the saved');
                    Help.AppendLine('  preset. Capture a preset via the URL from `Orchestrator.Report.Get`.');
                    Help.AppendLine('- **Long runs need the queue.** Batch jobs can outlive a synchronous request — use');
                    Help.AppendLine('  `Orchestrator.Playbook.Enqueue` or the async queue endpoint.');
                end;
        end;
        Help.AppendLine('');
    end;

    local procedure BuildWorkspacePreviewHelp(var Help: TextBuilder)
    begin
        Help.AppendLine('Returns the seeded workspace that every playbook sees at start — before any steps execute.');
        Help.AppendLine('Use this to discover the exact runtime values of `@_sys.*` and `@_who.*` for the current user and date.');
        Help.AppendLine('');
        Help.AppendLine('**Direction**: Outbound');
        Help.AppendLine('');
        Help.AppendLine('## Request');
        Help.AppendLine('');
        Help.AppendLine('| Parameter | Type | Required | Description |');
        Help.AppendLine('|---|---|---|---|');
        Help.AppendLine('| `initialRequest` | Object | No | Simulates a runtime initial request — stored at `_initial` in the workspace |');
        Help.AppendLine('');
        Help.AppendLine('## Response');
        Help.AppendLine('');
        Help.AppendLine('The full workspace JSON with `_sys` (dates, environment) and `_who` (user, salesperson, company info).');
        Help.AppendLine('If `initialRequest` was provided, it appears as `_initial`.');
        Help.AppendLine('');
        Help.AppendLine('## Usage');
        Help.AppendLine('');
        Help.AppendLine('**Before building a playbook** — call this to discover available workspace paths:');
        Help.AppendLine('- `@_sys.lastMonthStart` / `@_sys.lastMonthEnd` for monthly report filters');
        Help.AppendLine('- `@_who.companyInfo.registrationNo` for e-document exchange endpoints');
        Help.AppendLine('- `@_who.salesperson.email` for notification recipients');
        Help.AppendLine('- `@_who.telegramChatId` for Telegram messages');
        Help.AppendLine('');
        Help.AppendLine('**When debugging** — compare the preview with the workspace snapshot from a failed step log.');
        Help.AppendLine('');
    end;

    local procedure BuildLLMPatternsGuide(var O: TextBuilder)
    begin
        O.AppendLine('## Using LLM.Prompt.Complete in Playbooks');
        O.AppendLine('');
        O.AppendLine('`LLM.Prompt.Complete` is the general-purpose AI step for tasks not covered by dedicated message types.');
        O.AppendLine('Always set `roleCode` in the request template to control cost and speed (e.g. `HAIKU` for simple tasks).');
        O.AppendLine('');
        O.AppendLine('### Pattern 1: Yes/No Gate (per-item decision)');
        O.AppendLine('');
        O.AppendLine('Use LLM as a forEach decision step. The success condition determines the branch:');
        O.AppendLine('');
        O.AppendLine('```json');
        O.AppendLine('// Step 35 template — forEach, condition: text Contains "No"');
        O.AppendLine('{ "roleCode": "HAIKU",');
        O.AppendLine('  "system": "Compare two addresses. Answer ONLY Yes or No.",');
        O.AppendLine('  "prompt": "BC: @_current.fields.Address, @_current.fields.PostCode\\nRegistry: @30.@_iter.street, @30.@_iter.postCode" }');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('- Condition `text Contains "No"` → mismatch = Completed → downstream step runs');
        O.AppendLine('- Condition false ("Yes") → Cancelled → downstream `Skip If Step Failed` skips it');
        O.AppendLine('- Use `@_iter` to reference same-iteration data from prior forEach steps');
        O.AppendLine('');
        O.AppendLine('### Pattern 2: Text Formatting (summary/report generation)');
        O.AppendLine('');
        O.AppendLine('Collect workspace data from multiple steps and format for output:');
        O.AppendLine('');
        O.AppendLine('```json');
        O.AppendLine('// Step 48 template — single step, workspace dump');
        O.AppendLine('{ "roleCode": "HAIKU",');
        O.AppendLine('  "system": "Create a report for Telegram. Use only <b>, <i> tags. No <p>, <table>.",');
        O.AppendLine('  "prompt": "@10,20,30" }');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('- `@10,20,30` dumps filtered workspace data from steps 10, 20, 30 as a single string');
        O.AppendLine('- Always specify output constraints (Telegram tags, max chars, JSON-only, etc.)');
        O.AppendLine('- Store result via `ResultLogPaths: text>report` for downstream steps');
        O.AppendLine('');
        O.AppendLine('### Pattern 3: Run Notification');
        O.AppendLine('');
        O.AppendLine('Turn the run report into a human message. Do not describe the format — **show it**,');
        O.AppendLine('then show one filled-in example. A prompt that only lists rules produces output of');
        O.AppendLine('roughly the right shape and reliably the wrong length; the same prompt with a worked');
        O.AppendLine('example produces the shape exactly:');
        O.AppendLine('');
        O.AppendLine('The `system` string, written out (each line below is a real newline in the JSON):');
        O.AppendLine('');
        O.AppendLine('```text');
        O.AppendLine('JSON about an automated process that SUCCEEDED. Icelandic, for Telegram.');
        O.AppendLine('Format, exactly three lines:');
        O.AppendLine('OK <b>PLAYBOOK CODE</b>');
        O.AppendLine('<one sentence about what was achieved, with figures>');
        O.AppendLine('<i>x steps - y s</i>');
        O.AppendLine('Example:');
        O.AppendLine('OK <b>CUST-KT-SYNC</b>');
        O.AppendLine('5 customers checked, 4 valid kennitalas, 2 addresses updated.');
        O.AppendLine('<i>7 steps - 12 s</i>');
        O.AppendLine('Rules: use ONLY <b> and <i>, no other HTML and no Markdown asterisks. Real');
        O.AppendLine('line breaks, not <br>. durationMs is in MILLISECONDS - convert to seconds.');
        O.AppendLine('Take figures from _steps.*.result. No greeting, no signature.');
        O.AppendLine('Return ONLY the message.');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('and the step template that carries it:');
        O.AppendLine('');
        O.AppendLine('```json');
        O.AppendLine('// Step 900 - Start: _run.failed Equals false, Exclude From Run Status');
        O.AppendLine('{ "roleCode": "HAIKU", "system": "<the text above>", "prompt": "@_run,_steps" }');
        O.AppendLine('```');
        O.AppendLine('');
        O.AppendLine('Then `Result Log Paths: text>noticeText`, and send it from the next step with');
        O.AppendLine('`{"message":"@900.noticeText"}`. Failure notices are the same with `_run.failed`');
        O.AppendLine('inverted and `_run.firstFailedStepNo` named in the prompt.');
        O.AppendLine('');
        O.AppendLine('Four things the model gets wrong unless told:');
        O.AppendLine('');
        O.AppendLine('- **`durationMs` is milliseconds.** Unprompted it reports 41230 seconds.');
        O.AppendLine('- **`itemsProcessed` is iterations, not items.** Point the prompt at a named step.');
        O.AppendLine('- **Length.** State the limit *and* show it. SMS in Icelandic is UCS-2: 70 characters');
        O.AppendLine('  in one segment, 67 each once it splits — not the 160 of GSM-7 English.');
        O.AppendLine('- **Markup.** Telegram takes `<b> <i> <code> <a>`; anything else is a 400 from the');
        O.AppendLine('  API, so forbid other tags and Markdown asterisks explicitly.');
        O.AppendLine('');
        O.AppendLine('Pick the role for the job. A small local model is fine for a Yes/No gate but writes');
        O.AppendLine('unidiomatic Icelandic and leaks its instructions into prose; `HAIKU` composes these');
        O.AppendLine('notices in about 1.5 seconds. Latency compounds — a per-item LLM gate in a forEach');
        O.AppendLine('over a slow local model turned a 12-second run into 397 seconds.');
        O.AppendLine('');
        O.AppendLine('### Key Rules for LLM Steps');
        O.AppendLine('');
        O.AppendLine('1. **Always set `roleCode`** — `HAIKU` for simple tasks (fast, cheap), larger models only when needed');
        O.AppendLine('2. **Always set success condition** — `status = Success` catches provider errors');
        O.AppendLine('3. **Constrain output format, and show the shape** — "Answer ONLY Yes/No", "Return ONLY JSON". For anything with a length limit, give the limit and a worked example of it; a rule alone is not enough');
        O.AppendLine('4. **Telegram-safe HTML** — only `<b>`, `<i>`, `<code>`, `<a>` tags. No `<p>`, `<table>`, `<div>`');
        O.AppendLine('5. **Response field is `text`** — use `ResultLogPaths: text>fieldName` to store LLM output in workspace');
        O.AppendLine('');
    end;

    local procedure BuildAgentRules(var O: TextBuilder)
    begin
        O.AppendLine('## Rules for AI Agents');
        O.AppendLine('');
        O.AppendLine('1. **Use Data.Records.Get/Set for all CRUD** — reading/writing playbooks, steps, templates, credentials');
        O.AppendLine('2. **Use action message types for operations** — Run, Restart, Schedule, etc.');
        O.AppendLine('3. **Always check logs after Run** — read Playbook Instance ori and Playbook Step Log ori to verify');
        O.AppendLine('4. **Step numbering convention** — use 10, 20, 30... (allows inserting steps between)');
        O.AppendLine('5. **Request templates use `@path` syntax** — all data flows through the workspace, no separate bindings');
        O.AppendLine('6. **Request templates are BLOB fields** — set via Data.Records.Set by passing base64-encoded JSON as the field value');
        O.AppendLine('7. **Commits are permanent** — posting, document exchange, and other write operations cannot be undone by the engine');
        O.AppendLine('8. **Use `result[0]>name` in Result Log Paths** for single-record steps to avoid array wrapper in workspace');
        O.AppendLine('9. **Always add a Success condition** — one `Playbook Condition ori` row per step with `ConditionType=Success`, `Path=status`, `Operator=Equals`, `Value=Success` catches application-level errors. Set `StepType=Check` when a false answer is a legitimate result rather than a failure');
        O.AppendLine('10. **Use `@_iter` for cross-step forEach data** — in forEach templates, `@30.@_iter.fieldName` references another forEach step''s data at the same iteration index');
        O.AppendLine('11. **Use `Disabled=true` to skip steps** — disabled steps follow the success path without executing. Use this instead of deleting steps.');
        O.AppendLine('12. **LLM steps should set `roleCode`** — add `"roleCode":"HAIKU"` (or other role) in the request template to control which model is used');
        O.AppendLine('13. **Data.Records.Get uses `tableView` not `filter`** — the parameter name for BC filters is `tableView`, e.g. `"tableView":"WHERE(Registration Number=FILTER(<>''''))"`. Use English field names in tableView.');
        O.AppendLine('14. **Guard on the result, not just the status** — add `noOfRecords GreaterThan 0` beside `status Equals Success` on every query step whose emptiness would make the rest of the run pointless. See "`status Equals Success` is not enough".');
        O.AppendLine('15. **Write enum fields by AL name** — `NotEquals`, not the `Not Equals` caption a Get returns. Reads are localized; writes are not.');
        O.AppendLine('16. **Queue long playbooks instead of running them inline** — `Orchestrator.Playbook.Enqueue`, or an async invocation. A synchronous `Playbook.Run` that outlives the caller''s HTTP timeout leaves its instance stuck in `Running` for ever: the client gives up, the server keeps going, and nothing ever writes the completion. Any playbook with an LLM step in a forEach is a candidate.');
        O.AppendLine('17. **Verify from the step log, not the response** — a `Playbook.Run` response that never arrived says nothing about whether the run succeeded. Read `Playbook Step Log ori` filtered by instance; it is written step by step as the run progresses.');
        O.AppendLine('');
        O.AppendLine('## Execution Semantics');
        O.AppendLine('');
        O.AppendLine('- **Playbook status = Failed** only when `StepsFailed > 0`. A playbook ending via a condition branch (NextStepNo_Failure = 0 with 0 step errors) is Completed.');
        O.AppendLine('- **forEach condition false = Cancelled** (not Failed). Does not increment StepsFailed. `Skip If Step Failed` still skips these iterations in downstream steps.');
        O.AppendLine('- **Single-step condition false = branch** — follows NextStepNo_Failure path. If that path is 0, playbook ends as Completed (not Failed).');
        O.AppendLine('- **Paged steps use the step''s Request Template** — not the playbook''s initial request. The engine injects `skip`/`take` into the template.');
        O.AppendLine('- **Paged step failure** — if a paged step fails, the engine follows the paged step''s failure path (not the chain end step''s).');
        O.AppendLine('- **Workspace snapshot** — on step failure, the workspace JSON is saved to the step log for debugging. Download via the Step Log subpage.');
        O.AppendLine('- **Start condition false = Cancelled, success path** — the step logs `Skipped: start conditions not met`, `stepsSkipped` increments, and the run is not failed. This is the mechanism the reporting tail is built on.');
        O.AppendLine('- **Check steps do not fail the run** — a `Check` whose Success condition is false is Cancelled and routes down the failure edge, but `StepsFailed` is untouched. Only a technical failure — the message type raising an error — fails a Check step.');
        O.AppendLine('- **Excluded steps are recorded under `_tail`** — out of the totals, still referenceable. They appear in the step log like any other step.');
        O.AppendLine('');
        O.AppendLine('## Built-in Workspace Variables');
        O.AppendLine('');
        O.AppendLine('These are seeded automatically at playbook start. No steps needed to populate them.');
        O.AppendLine('');
        O.AppendLine('### `_sys` — System Constants');
        O.AppendLine('');
        O.AppendLine('| Path | Example | Description |');
        O.AppendLine('|---|---|---|');
        O.AppendLine('| `_sys.today` | `2026-08-30` | Calendar date (Today) |');
        O.AppendLine('| `_sys.workDate` | `2026-08-30` | BC posting date (WorkDate) |');
        O.AppendLine('| `_sys.now` | `2026-08-30T15:30:00Z` | Current timestamp |');
        O.AppendLine('| `_sys.year` | `2026` | Current year |');
        O.AppendLine('| `_sys.lastMonthStart` | `2026-07-01` | First day of previous month |');
        O.AppendLine('| `_sys.lastMonthEnd` | `2026-07-31` | Last day of previous month |');
        O.AppendLine('| `_sys.thisMonthStart` | `2026-08-01` | First day of current month |');
        O.AppendLine('| `_sys.thisQuarterStart` | `2026-07-01` | First day of current quarter |');
        O.AppendLine('| `_sys.thisYearStart` | `2026-01-01` | First day of current year |');
        O.AppendLine('| `_sys.companyName` | `CRONUS IS` | Current BC company |');
        O.AppendLine('| `_sys.userId` | `ADMIN` | Current user ID |');
        O.AppendLine('');
        O.AppendLine('### `_who` — User & Company Context (from Help.WhoAmI.Get)');
        O.AppendLine('');
        O.AppendLine('| Path | Example | Description |');
        O.AppendLine('|---|---|---|');
        O.AppendLine('| `_who.user.userName` | `GUNNAR` | Login name |');
        O.AppendLine('| `_who.user.userSecurityId` | GUID | User security ID |');
        O.AppendLine('| `_who.salesperson.name` | `Gunnar Gestsson` | Salesperson full name |');
        O.AppendLine('| `_who.salesperson.email` | `user@company.is` | Salesperson email |');
        O.AppendLine('| `_who.salesperson.code` | `GG` | Salesperson code |');
        O.AppendLine('| `_who.salesperson.phoneNo` | `5551234` | Phone number |');
        O.AppendLine('| `_who.companyInfo.name` | `CRONUS Ltd.` | Legal company name |');
        O.AppendLine('| `_who.companyInfo.registrationNo` | `4112032630` | Company kennitala |');
        O.AppendLine('| `_who.companyInfo.vatRegistrationNo` | `101067` | VAT number |');
        O.AppendLine('| `_who.companyInfo.address` | `5 The Ring` | Company address |');
        O.AppendLine('| `_who.telegramChatId` | `8866830259` | User''s Telegram chat ID |');
        O.AppendLine('| `_who.personalization.languageId` | `1033` | Session language LCID |');
        O.AppendLine('');
        BuildDataReference(O);
    end;

    local procedure BuildDataReference(var O: TextBuilder)
    begin
        O.AppendLine('## Data Reference — Tables & Fields for Data.Records.Get/Set');
        O.AppendLine('');
        O.AppendLine('IMPORTANT: Playbook steps use **message type parameter names** (e.g. `tableName`, `fieldNumbers`),');
        O.AppendLine('NOT the MCP tool shorthand names (e.g. `table`, `fields`). The playbook engine dispatches');
        O.AppendLine('through `invoke_message_type`, which passes data directly to the message type handler.');
        O.AppendLine('Always call `Help.Implementation.Get` with the message type name to see its exact parameters.');
        O.AppendLine('');
        O.AppendLine('### Orchestrator Tables');
        O.AppendLine('');
        O.AppendLine('#### Scheduled Entry ori');
        O.AppendLine('Stores configuration for each monitored Job Queue Entry.');
        O.AppendLine('');
        O.AppendLine('| Field | JSON Key | Type | Notes |');
        O.AppendLine('|---|---|---|---|');
        O.AppendLine('| ID | ID | GUID | PK — matches the Job Queue Entry ID |');
        O.AppendLine('| Object Type to Run | ObjectTypetoRun | Option | Codeunit/Report |');
        O.AppendLine('| Object ID to Run | ObjectIDtoRun | Integer | BC object ID |');
        O.AppendLine('| Description | Description | Text[250] | |');
        O.AppendLine('| Blocked | Blocked | Boolean | Prevents scheduling when true |');
        O.AppendLine('| No. of Minutes between Runs | No_ofMinutesbetweenRuns | Integer | |');
        O.AppendLine('| Run on Mondays..Sundays | RunonMondays..RunonSundays | Boolean | |');
        O.AppendLine('| Starting Time | StartingTime | Time | |');
        O.AppendLine('| Ending Time | EndingTime | Time | |');
        O.AppendLine('| Notification Type | NotificationType | Option | None/Email |');
        O.AppendLine('| Notification Recipient | NotificationRecipient | Text | Email address |');
        O.AppendLine('| Retry Policy | RetryPolicy | Option | Always/Limited/None |');
        O.AppendLine('| Client Credentials Code | ClientCredentialsCode | Code[20] | For API-based scheduling |');
        O.AppendLine('');
        O.AppendLine('#### Scheduler Setup ori');
        O.AppendLine('Singleton setup table. Read with `Data.Records.Get`, tableName = "Scheduler Setup ori".');
        O.AppendLine('');
        O.AppendLine('### Playbook Tables');
        O.AppendLine('');
        O.AppendLine('#### Playbook ori (PK: Code)');
        O.AppendLine('');
        O.AppendLine('| Field | JSON Key | Type | Notes |');
        O.AppendLine('|---|---|---|---|');
        O.AppendLine('| Code | Code | Code[20] | PK |');
        O.AppendLine('| Description | Description | Text[250] | |');
        O.AppendLine('| Recurring Template Code | RecurringTemplateCode | Code[20] | Links to schedule template |');
        O.AppendLine('| No. of Minutes between Runs | No_ofMinutesbetweenRuns | Integer | |');
        O.AppendLine('| Run on Mondays..Sundays | RunonMondays..RunonSundays | Boolean | |');
        O.AppendLine('| Starting/Ending Time | StartingTime/EndingTime | Time | |');
        O.AppendLine('| Notification Type | NotificationType | Option | None/Email |');
        O.AppendLine('| Scheduled | Scheduled | Boolean | FlowField — read-only |');
        O.AppendLine('');
        O.AppendLine('#### Playbook Step ori (PK: PlaybookCode + StepNo_)');
        O.AppendLine('');
        O.AppendLine('| Field | JSON Key | Type | Notes |');
        O.AppendLine('|---|---|---|---|');
        O.AppendLine('| Playbook Code | PlaybookCode | Code[20] | PK |');
        O.AppendLine('| Step No. | StepNo_ | Integer | PK — use 10, 20, 30... |');
        O.AppendLine('| Description | Description | Text[250] | |');
        O.AppendLine('| Message Type | MessageType | Option | The Bifrost message type to call |');
        O.AppendLine('| Next Step No. (Success) | NextStepNo_Success | Integer | 0 = end playbook |');
        O.AppendLine('| Next Step No. (Failure) | NextStepNo_Failure | Integer | 0 = fail playbook |');
        O.AppendLine('| Request Template | RequestTemplate | BLOB | JSON template with `@path` workspace refs (set as base64) |');
        O.AppendLine('| Result Log Paths | ResultLogPaths | Text[2048] | Paths to extract from response to workspace. `source>target` renames, `source[0]>target` extracts first element |');
        O.AppendLine('| Iterate Array Path | IterateArrayPath | Text[250] | Dot-path to array for foreach |');
        O.AppendLine('| Iterate Source Step No. | IterateSourceStepNo_ | Integer | Which step''s response has the array |');
        O.AppendLine('| Step Type | StepType | Option | Action (default) or Check — is a false Success condition a failure? |');
        O.AppendLine('| Summary Paths | SummaryPaths | Text[2048] | Response paths copied into the run report. Keep small |');
        O.AppendLine('| Exclude From Run Status | ExcludeFromRunStatus | Boolean | Keep this step out of _run and _steps |');
        O.AppendLine('| Stop On Item Error | StopOnItemError | Boolean | For foreach: abort on first failure |');
        O.AppendLine('| Skip If Step Failed | SkipIfStepFailed | Integer | Skip this iteration if named step''s same iteration failed |');
        O.AppendLine('| Paged | Paged | Boolean | Enable auto-paging (skip/take) |');
        O.AppendLine('| Page Size | PageSize | Integer | Records per page (default 500) |');
        O.AppendLine('| Page Through Step No. | PageThroughStepNo_ | Integer | Last step in paged chain |');
        O.AppendLine('| Disabled | Disabled | Boolean | Skip this step without executing |');
        O.AppendLine('');
        O.AppendLine('#### Playbook Condition ori (PK: PlaybookCode + StepNo_ + ConditionType + GroupNo_ + LineNo_)');
        O.AppendLine('');
        O.AppendLine('| Field | JSON Key | Type | Notes |');
        O.AppendLine('|---|---|---|---|');
        O.AppendLine('| Playbook Code | PlaybookCode | Code[20] | PK |');
        O.AppendLine('| Step No. | StepNo_ | Integer | PK — the step this condition guards |');
        O.AppendLine('| Condition Type | ConditionType | Enum | PK — Start, Success or Error |');
        O.AppendLine('| Group No. | GroupNo_ | Integer | PK — conditions in one group are ANDed; groups are ORed |');
        O.AppendLine('| Line No. | LineNo_ | Integer | PK — use 10000, 20000, ... |');
        O.AppendLine('| Path | Path | Text[250] | Dot-path. Start/Error read the workspace, Success reads the step response |');
        O.AppendLine('| Operator | Operator | Enum | Equals, NotEquals, Contains, GreaterThan, LessThan, GreaterOrEqual, LessOrEqual, Exists |');
        O.AppendLine('| Value | Value | Text[250] | Compared as text; numeric operators parse both sides |');
        O.AppendLine('| Description | Description | Text[100] | Why this condition exists. Optional, and worth writing |');
        O.AppendLine('');
        O.AppendLine('Deleting a step cascades to its conditions. An empty condition set is true, so a step');
        O.AppendLine('with no Success conditions succeeds whenever the message type does not raise an error.');
        O.AppendLine('');
        O.AppendLine('### Execution Log Tables (read-only)');
        O.AppendLine('');
        O.AppendLine('#### Playbook Instance ori (PK: ID)');
        O.AppendLine('One record per playbook run. Fields: PlaybookCode, Status, StartedAt, CompletedAt,');
        O.AppendLine('TotalDuration, StepsExecuted, StepsFailed, ItemsProcessed, InitiatedBy, ErrorText, Context.');
        O.AppendLine('');
        O.AppendLine('`Status` stays `Running` until the run writes its own completion, so an instance');
        O.AppendLine('abandoned mid-flight — a session killed, a caller that timed out — stays `Running`');
        O.AppendLine('for ever. Judge such a run by the timestamps on its step log, not by this field.');
        O.AppendLine('');
        O.AppendLine('#### Playbook Step Log ori (PK: InstanceID + StepNo_ + IterationNo_)');
        O.AppendLine('One record per step execution. Fields: MessageType, Status, Duration, ErrorText,');
        O.AppendLine('RequestSent (base64 BLOB), ResponseReceived (base64 BLOB), IteratorElement, WorkspaceSnapshot (base64 BLOB, only on failed steps).');
        O.AppendLine('');
    end;

    var
        HelpHeadingLbl: Label '# %1 - Help', Locked = true;
        HelpDataIdExampleLbl: Label '{ "type": "%1", "data": { "id": "a1b2c3d4-..." } }', Locked = true;
        HelpTypeOnlyExampleLbl: Label '{ "type": "%1" }', Locked = true;
}
