namespace Origo.Bifrost.Nornir;

using Origo.Bifrost;
using System.Reflection;
using System.Security.AccessControl;
using System.Telemetry;
using System.Utilities;

/// <summary>
/// Takes the data of the published <c>Origo Cloud Events Orchestrator</c> app over into
/// Bifrost Nornir the first time this app is installed in a company. For every (old table,
/// new table) pair the old table is copied with <c>DataTransfer</c> when it still exists in
/// the database and the new table is empty; BLOB fields, which DataTransfer does not support,
/// are copied afterwards with a RecordRef pass. Values that stored an object id or an enum
/// ordinal from an old object-id range are shifted into the new ranges, and every user that
/// held one of the old permission sets is granted the matching Bifrost one. Execution logs
/// (playbook instances and step logs) are not copied.
/// Generated by <c>tools/gen_install.py</c> - do not edit by hand.
/// </summary>
codeunit 10035604 "Nornir Takeover ori"
{
    Access = Internal;

    /// <summary>
    /// Runs the whole take-over. Called from the install codeunit before the app registers
    /// its own job queues, so the copied schedules are already present.
    /// </summary>
    internal procedure TakeOverAll()
    begin
        TakeOverScheduledEntry();
        TakeOverSchedulerSetup();
        TakeOverRecurringTemplate();
        TakeOverClientCredentials();
        TakeOverPlaybook();
        TakeOverPlaybookStep();
        TakeOverJQParameter();
        TakeOverReportRequestPreset();
        TakeOverPlaybookCondition();
        TakeOverTelegramChatId();
        TakeOverAccessControl();
    end;

    /// <summary>Copies <c>CE Orchestrator Entry ori</c> (10076035) into <c>Scheduled Entry ori</c> (10035535).</summary>
    local procedure TakeOverScheduledEntry()
    var
        Target: Record "Scheduled Entry ori";
        DataTransfer: DataTransfer;
    begin
        if not OldTableExists(10076035) then
            exit;
        if not Target.IsEmpty() then
            exit;
        DataTransfer.SetTables(10076035, Database::"Scheduled Entry ori");
        DataTransfer.AddFieldValue(10, 10);
        DataTransfer.AddFieldValue(15, 15);
        DataTransfer.AddFieldValue(20, 20);
        DataTransfer.AddFieldValue(27, 27);
        DataTransfer.AddFieldValue(30, 30);
        DataTransfer.AddFieldValue(45, 45);
        DataTransfer.AddFieldValue(50, 50);
        DataTransfer.AddFieldValue(60, 60);
        DataTransfer.AddFieldValue(70, 70);
        DataTransfer.AddFieldValue(80, 80);
        DataTransfer.AddFieldValue(90, 90);
        DataTransfer.AddFieldValue(100, 100);
        DataTransfer.AddFieldValue(110, 110);
        DataTransfer.AddFieldValue(140, 140);
        DataTransfer.AddFieldValue(150, 150);
        DataTransfer.AddFieldValue(160, 160);
        DataTransfer.AddFieldValue(171, 171);
        DataTransfer.AddFieldValue(180, 180);
        DataTransfer.AddFieldValue(190, 190);
        DataTransfer.AddFieldValue(200, 200);
        DataTransfer.AddFieldValue(210, 210);
        DataTransfer.AddFieldValue(220, 220);
        DataTransfer.AddFieldValue(230, 230);
        DataTransfer.AddFieldValue(240, 240);
        DataTransfer.AddFieldValue(250, 250);
        DataTransfer.AddFieldValue(260, 260);
        DataTransfer.AddFieldValue(270, 270);
        DataTransfer.AddFieldValue(280, 280);
        DataTransfer.AddFieldValue(290, 290);
        DataTransfer.AddFieldValue(300, 300);
        DataTransfer.UpdateAuditFields(false);
        DataTransfer.CopyRows();
        ShiftIntegerField(Database::"Scheduled Entry ori", Target.FieldNo("Object ID to Run"), 10076035, 10076134, -40500);
        LogTakeOver('Scheduled Entry ori', Target.Count());
    end;

    /// <summary>Copies <c>CE Orchestrator Setup ori</c> (10076036) into <c>Scheduler Setup ori</c> (10035536).</summary>
    local procedure TakeOverSchedulerSetup()
    var
        Target: Record "Scheduler Setup ori";
        DataTransfer: DataTransfer;
    begin
        if not OldTableExists(10076036) then
            exit;
        if not Target.IsEmpty() then
            exit;
        DataTransfer.SetTables(10076036, Database::"Scheduler Setup ori");
        DataTransfer.AddFieldValue(10, 10);
        DataTransfer.AddFieldValue(20, 20);
        DataTransfer.AddFieldValue(30, 30);
        DataTransfer.AddFieldValue(40, 40);
        DataTransfer.AddFieldValue(50, 50);
        DataTransfer.AddFieldValue(60, 60);
        DataTransfer.UpdateAuditFields(false);
        DataTransfer.CopyRows();
        LogTakeOver('Scheduler Setup ori', Target.Count());
    end;

    /// <summary>Copies <c>CE Recurring Template ori</c> (10076037) into <c>Recurring Template ori</c> (10035537).</summary>
    local procedure TakeOverRecurringTemplate()
    var
        Target: Record "Recurring Template ori";
        DataTransfer: DataTransfer;
    begin
        if not OldTableExists(10076037) then
            exit;
        if not Target.IsEmpty() then
            exit;
        DataTransfer.SetTables(10076037, Database::"Recurring Template ori");
        DataTransfer.AddFieldValue(10, 10);
        DataTransfer.AddFieldValue(20, 20);
        DataTransfer.AddFieldValue(31, 31);
        DataTransfer.AddFieldValue(40, 40);
        DataTransfer.AddFieldValue(50, 50);
        DataTransfer.AddFieldValue(60, 60);
        DataTransfer.AddFieldValue(70, 70);
        DataTransfer.AddFieldValue(80, 80);
        DataTransfer.AddFieldValue(90, 90);
        DataTransfer.AddFieldValue(100, 100);
        DataTransfer.AddFieldValue(110, 110);
        DataTransfer.AddFieldValue(120, 120);
        DataTransfer.AddFieldValue(130, 130);
        DataTransfer.AddFieldValue(140, 140);
        DataTransfer.UpdateAuditFields(false);
        DataTransfer.CopyRows();
        LogTakeOver('Recurring Template ori', Target.Count());
    end;

    /// <summary>Copies <c>CE Client Credentials ori</c> (10076038) into <c>Client Credentials ori</c> (10035538).</summary>
    local procedure TakeOverClientCredentials()
    var
        Target: Record "Client Credentials ori";
        DataTransfer: DataTransfer;
    begin
        if not OldTableExists(10076038) then
            exit;
        if not Target.IsEmpty() then
            exit;
        DataTransfer.SetTables(10076038, Database::"Client Credentials ori");
        DataTransfer.AddFieldValue(10, 10);
        DataTransfer.AddFieldValue(20, 20);
        DataTransfer.AddFieldValue(30, 30);
        DataTransfer.AddFieldValue(40, 40);
        DataTransfer.UpdateAuditFields(false);
        DataTransfer.CopyRows();
        LogTakeOver('Client Credentials ori', Target.Count());
    end;

    /// <summary>Copies <c>CE Playbook ori</c> (10076039) into <c>Playbook ori</c> (10035539).</summary>
    local procedure TakeOverPlaybook()
    var
        Target: Record "Playbook ori";
        DataTransfer: DataTransfer;
        BlobFieldNos: List of [Integer];
    begin
        if not OldTableExists(10076039) then
            exit;
        if not Target.IsEmpty() then
            exit;
        DataTransfer.SetTables(10076039, Database::"Playbook ori");
        DataTransfer.AddFieldValue(1, 1);
        DataTransfer.AddFieldValue(10, 10);
        DataTransfer.AddFieldValue(70, 70);
        DataTransfer.AddFieldValue(71, 71);
        DataTransfer.AddFieldValue(72, 72);
        DataTransfer.AddFieldValue(80, 80);
        DataTransfer.UpdateAuditFields(false);
        DataTransfer.CopyRows();
        BlobFieldNos.Add(30);
        CopyBlobFields(10076039, Database::"Playbook ori", BlobFieldNos);
        LogTakeOver('Playbook ori', Target.Count());
    end;

    /// <summary>Copies <c>CE Playbook Step ori</c> (10076040) into <c>Playbook Step ori</c> (10035540).</summary>
    local procedure TakeOverPlaybookStep()
    var
        Target: Record "Playbook Step ori";
        DataTransfer: DataTransfer;
        BlobFieldNos: List of [Integer];
    begin
        if not OldTableExists(10076040) then
            exit;
        if not Target.IsEmpty() then
            exit;
        DataTransfer.SetTables(10076040, Database::"Playbook Step ori");
        DataTransfer.AddFieldValue(1, 1);
        DataTransfer.AddFieldValue(2, 2);
        DataTransfer.AddFieldValue(10, 10);
        DataTransfer.AddFieldValue(15, 15);
        DataTransfer.AddFieldValue(20, 20);
        DataTransfer.AddFieldValue(40, 40);
        DataTransfer.AddFieldValue(41, 41);
        DataTransfer.AddFieldValue(60, 60);
        DataTransfer.AddFieldValue(61, 61);
        DataTransfer.AddFieldValue(70, 70);
        DataTransfer.AddFieldValue(80, 80);
        DataTransfer.AddFieldValue(90, 90);
        DataTransfer.AddFieldValue(91, 91);
        DataTransfer.AddFieldValue(100, 100);
        DataTransfer.AddFieldValue(101, 101);
        DataTransfer.AddFieldValue(102, 102);
        DataTransfer.AddFieldValue(110, 110);
        DataTransfer.AddFieldValue(111, 111);
        DataTransfer.UpdateAuditFields(false);
        DataTransfer.CopyRows();
        BlobFieldNos.Add(30);
        CopyBlobFields(10076040, Database::"Playbook Step ori", BlobFieldNos);
        ShiftIntegerField(Database::"Playbook Step ori", Target.FieldNo("Message Type"), 10076035, 10076134, -40500);
        ShiftIntegerField(Database::"Playbook Step ori", Target.FieldNo("Message Type"), 10075485, 10075984, 2400);
        LogTakeOver('Playbook Step ori', Target.Count());
    end;

    /// <summary>Copies <c>CE JQ Parameter ori</c> (10076044) into <c>JQ Parameter ori</c> (10035544).</summary>
    local procedure TakeOverJQParameter()
    var
        Target: Record "JQ Parameter ori";
        DataTransfer: DataTransfer;
        BlobFieldNos: List of [Integer];
    begin
        if not OldTableExists(10076044) then
            exit;
        if not Target.IsEmpty() then
            exit;
        DataTransfer.SetTables(10076044, Database::"JQ Parameter ori");
        DataTransfer.AddFieldValue(1, 1);
        DataTransfer.UpdateAuditFields(false);
        DataTransfer.CopyRows();
        BlobFieldNos.Add(10);
        CopyBlobFields(10076044, Database::"JQ Parameter ori", BlobFieldNos);
        LogTakeOver('JQ Parameter ori', Target.Count());
    end;

    /// <summary>Copies <c>CE Report Request Preset ori</c> (10076090) into <c>Report Request Preset ori</c> (10035590).</summary>
    local procedure TakeOverReportRequestPreset()
    var
        Target: Record "Report Request Preset ori";
        DataTransfer: DataTransfer;
        BlobFieldNos: List of [Integer];
    begin
        if not OldTableExists(10076090) then
            exit;
        if not Target.IsEmpty() then
            exit;
        DataTransfer.SetTables(10076090, Database::"Report Request Preset ori");
        DataTransfer.AddFieldValue(1, 1);
        DataTransfer.AddFieldValue(2, 2);
        DataTransfer.AddFieldValue(3, 3);
        DataTransfer.UpdateAuditFields(false);
        DataTransfer.CopyRows();
        BlobFieldNos.Add(10);
        CopyBlobFields(10076090, Database::"Report Request Preset ori", BlobFieldNos);
        LogTakeOver('Report Request Preset ori', Target.Count());
    end;

    /// <summary>Copies <c>CE Playbook Condition ori</c> (10076099) into <c>Playbook Condition ori</c> (10035599).</summary>
    local procedure TakeOverPlaybookCondition()
    var
        Target: Record "Playbook Condition ori";
        DataTransfer: DataTransfer;
    begin
        if not OldTableExists(10076099) then
            exit;
        if not Target.IsEmpty() then
            exit;
        DataTransfer.SetTables(10076099, Database::"Playbook Condition ori");
        DataTransfer.AddFieldValue(1, 1);
        DataTransfer.AddFieldValue(2, 2);
        DataTransfer.AddFieldValue(3, 3);
        DataTransfer.AddFieldValue(4, 4);
        DataTransfer.AddFieldValue(5, 5);
        DataTransfer.AddFieldValue(10, 10);
        DataTransfer.AddFieldValue(11, 11);
        DataTransfer.AddFieldValue(12, 12);
        DataTransfer.AddFieldValue(20, 20);
        DataTransfer.UpdateAuditFields(false);
        DataTransfer.CopyRows();
        LogTakeOver('Playbook Condition ori', Target.Count());
    end;

    /// <summary>Copies the Telegram chat id from the published app's user setup extension.</summary>
    local procedure TakeOverTelegramChatId()
    var
        OldRef: RecordRef;
        NewRef: RecordRef;
        OldField: FieldRef;
        NewField: FieldRef;
        Copied: Integer;
    begin
        if not OldTableExists(10075509) then
            exit;
        OldRef.Open(10075509);
        if not OldRef.FieldExist(10076035) then begin
            OldRef.Close();
            exit;
        end;
        NewRef.Open(10077909);
        if NewRef.FindSet(true) then
            repeat
                NewField := NewRef.Field(10035535);
                if Format(NewField.Value()) = '' then
                    if FindMatchingRow(NewRef, OldRef) then begin
                        OldField := OldRef.Field(10076035);
                        if Format(OldField.Value()) <> '' then begin
                            NewField.Value(OldField.Value());
                            NewRef.Modify(false);
                            Copied += 1;
                        end;
                    end;
            until NewRef.Next() = 0;
        NewRef.Close();
        OldRef.Close();
        if Copied > 0 then
            LogTakeOver('User Setup ori.Telegram Chat ID ori', Copied);
    end;

    /// <summary>Grants the Bifrost permission sets to every user that held an old one.</summary>
    local procedure TakeOverAccessControl()
    var
        Migrated: Integer;
    begin
        Migrated += MigrateRole('CE Orchestrator ori', 'BIFROST Nornir ori');
        Migrated += MigrateRole('CE Orch. Setup ori', 'BIFROST NrnSetup ori');
        Migrated += MigrateRole('CE Orch. Mgt ori', 'BIFROST NrnMgt ori');
        Migrated += MigrateRole('CE PlaybookAdmin ori', 'BIFROST PlaybAdm ori');
        Migrated += MigrateRole('CE Playbook View ori', 'BIFROST PlaybVw ori');
        if Migrated > 0 then
            LogTakeOver('Access Control', Migrated);
    end;

    local procedure MigrateRole(OldRoleId: Code[20]; NewRoleId: Code[20]) Migrated: Integer
    var
        OldAccessControl: Record "Access Control";
        NewAccessControl: Record "Access Control";
        NewAppId: Guid;
    begin
        NewAppId := AppId();
        OldAccessControl.SetRange("Role ID", OldRoleId);
        OldAccessControl.SetRange("App ID", OldAppId());
        if OldAccessControl.FindSet() then
            repeat
                if not NewAccessControl.Get(
                    OldAccessControl."User Security ID", NewRoleId, OldAccessControl."Company Name",
                    OldAccessControl.Scope, NewAppId)
                then begin
                    NewAccessControl.Init();
                    NewAccessControl."User Security ID" := OldAccessControl."User Security ID";
                    NewAccessControl."Role ID" := NewRoleId;
                    NewAccessControl."Company Name" := OldAccessControl."Company Name";
                    NewAccessControl.Scope := OldAccessControl.Scope;
                    NewAccessControl."App ID" := NewAppId;
                    if NewAccessControl.Insert(true) then
                        Migrated += 1;
                end;
            until OldAccessControl.Next() = 0;
    end;

    /// <summary>Copies BLOB fields, which DataTransfer does not support, row by row.</summary>
    local procedure CopyBlobFields(OldTableId: Integer; NewTableId: Integer; BlobFieldNos: List of [Integer])
    var
        TempBlob: Codeunit "Temp Blob";
        OldRef: RecordRef;
        NewRef: RecordRef;
        BlobField: FieldRef;
        BlobFieldNo: Integer;
        Modified: Boolean;
    begin
        OldRef.Open(OldTableId);
        NewRef.Open(NewTableId);
        if NewRef.FindSet(true) then
            repeat
                if FindMatchingRow(NewRef, OldRef) then begin
                    Modified := false;
                    foreach BlobFieldNo in BlobFieldNos do begin
                        BlobField := OldRef.Field(BlobFieldNo);
                        BlobField.CalcField();
                        Clear(TempBlob);
                        TempBlob.FromRecordRef(OldRef, BlobFieldNo);
                        if TempBlob.HasValue() then begin
                            TempBlob.ToRecordRef(NewRef, BlobFieldNo);
                            Modified := true;
                        end;
                    end;
                    if Modified then
                        NewRef.Modify(false);
                end;
            until NewRef.Next() = 0;
        NewRef.Close();
        OldRef.Close();
    end;

    /// <summary>Finds the row in the old table that carries the same primary key values.</summary>
    local procedure FindMatchingRow(var NewRef: RecordRef; var OldRef: RecordRef): Boolean
    var
        NewKeyField: FieldRef;
        OldKeyField: FieldRef;
        NewKey: KeyRef;
        i: Integer;
    begin
        OldRef.Reset();
        NewKey := NewRef.KeyIndex(1);
        for i := 1 to NewKey.FieldCount() do begin
            NewKeyField := NewKey.FieldIndex(i);
            if not OldRef.FieldExist(NewKeyField.Number()) then
                exit(false);
            OldKeyField := OldRef.Field(NewKeyField.Number());
            OldKeyField.SetRange(NewKeyField.Value());
        end;
        exit(OldRef.FindFirst());
    end;

    /// <summary>Shifts values that carried an object id or enum ordinal from an old range.</summary>
    local procedure ShiftIntegerField(TableId: Integer; FieldNo: Integer; FromValue: Integer; ToValue: Integer; Offset: Integer)
    var
        RecRef: RecordRef;
        TargetField: FieldRef;
        FieldValue: Integer;
    begin
        RecRef.Open(TableId);
        if RecRef.FindSet(true) then
            repeat
                TargetField := RecRef.Field(FieldNo);
                FieldValue := TargetField.Value();
                if (FieldValue >= FromValue) and (FieldValue <= ToValue) then begin
                    TargetField.Value(FieldValue + Offset);
                    RecRef.Modify(false);
                end;
            until RecRef.Next() = 0;
        RecRef.Close();
    end;

    /// <summary>Reports whether the published app's table still exists in the database.</summary>
    local procedure OldTableExists(OldTableId: Integer): Boolean
    var
        TableMetadata: Record "Table Metadata";
    begin
        exit(TableMetadata.Get(OldTableId));
    end;

    local procedure LogTakeOver(TableName: Text; RowCount: Integer)
    var
        Telemetry: Codeunit Telemetry;
        Dimensions: Dictionary of [Text, Text];
    begin
        Dimensions.Add('table', TableName);
        Dimensions.Add('rows', Format(RowCount, 0, 9));
        Telemetry.LogMessage(
            'ORI-BIF-0002', TakeOverTelemetryTxt, Verbosity::Normal,
            DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, Dimensions);
    end;

    local procedure OldAppId(): Guid
    begin
        exit('755c941b-c4e5-4d19-938f-9c56c25708a9');
    end;

    local procedure AppId(): Guid
    var
        AppInfo: ModuleInfo;
    begin
        NavApp.GetCurrentModuleInfo(AppInfo);
        exit(AppInfo.Id());
    end;

    var
        TakeOverTelemetryTxt: Label 'Bifrost Nornir took data over from Origo Cloud Events Orchestrator.', Locked = true;
}
