namespace Origo.Bifrost.Orchestrator;

/// <summary>
/// Full permission set for the Bifrost Orchestrator extension: every table, page and
/// codeunit the application owns. Assign it together with a Bifröst Foundation
/// permission set (<c>BIFROST Full ori</c> or <c>BIFROST Read ori</c>) - the message
/// loop, the request log and the secret store live in Foundation, and job queue
/// scheduling additionally needs the base-application job queue permissions.
/// </summary>
permissionset 10035535 "BIFROST Orchestr ori"
{
    Assignable = true;
    Caption = 'Bifrost Orchestrator', MaxLength = 30, Comment = 'is-IS=Bifröst stjórnandi';

    Permissions =
        tabledata "Client Credentials ori" = RIMD,
        tabledata "JQ Parameter ori" = RIMD,
        tabledata "Playbook Condition ori" = RIMD,
        tabledata "Playbook Instance ori" = RIMD,
        tabledata "Playbook Step Log ori" = RIMD,
        tabledata "Playbook Step ori" = RIMD,
        tabledata "Playbook ori" = RIMD,
        tabledata "Recurring Template ori" = RIMD,
        tabledata "Report Request Preset ori" = RIMD,
        tabledata "Scheduled Entry ori" = RIMD,
        tabledata "Scheduler Setup ori" = RIMD,
        page "Categories ori" = X,
        page "Credentials Card ori" = X,
        page "Credentials List ori" = X,
        page "Entries API ori" = X,
        page "Log Entry ori" = X,
        page "Playbook Card ori" = X,
        page "Playbook Cond. Subpage ori" = X,
        page "Playbook Instance Card ori" = X,
        page "Playbook Instances ori" = X,
        page "Playbook Last Run FB ori" = X,
        page "Playbook Step Log Dtl. FB ori" = X,
        page "Playbook Step Logs Sub. ori" = X,
        page "Playbook Step Template FB ori" = X,
        page "Playbook Steps Subpage ori" = X,
        page "Playbook Template Editor ori" = X,
        page "Playbooks ori" = X,
        page "Recurring Template ori" = X,
        page "Recurring Templates ori" = X,
        page "Report Preset Card ori" = X,
        page "Sched. Entry Subform ori" = X,
        page "Schedule Playbook ori" = X,
        page "Scheduled Entry API ori" = X,
        page "Scheduled Entry Card ori" = X,
        page "Scheduler Setup Wizard ori" = X,
        page "Scheduler Setup ori" = X,
        page "Scheduler Status ori" = X,
        codeunit "App Install ori" = X,
        codeunit "App Takeover ori" = X,
        codeunit "App Upgrade ori" = X,
        codeunit "Email Notification ori" = X,
        codeunit "Email Send Msg ori" = X,
        codeunit "Email Send ori" = X,
        codeunit "Entry Msg Handler ori" = X,
        codeunit "Entry Restart Msg ori" = X,
        codeunit "Entry RestartIf Msg ori" = X,
        codeunit "Help Get Impl ori" = X,
        codeunit "Help ori" = X,
        codeunit "Msg Executor ori" = X,
        codeunit "None Notification ori" = X,
        codeunit "Overview Subscriber ori" = X,
        codeunit "Playbook Enqueue Msg ori" = X,
        codeunit "Playbook JQ Dispatcher ori" = X,
        codeunit "Playbook JSON Helper ori" = X,
        codeunit "Playbook Log Mgt ori" = X,
        codeunit "Playbook Msg Handler ori" = X,
        codeunit "Playbook Run Msg ori" = X,
        codeunit "Playbook Runner ori" = X,
        codeunit "Playbook Schedule Msg ori" = X,
        codeunit "Playbook Step Executor ori" = X,
        codeunit "Playbook Workspace ori" = X,
        codeunit "Report Data Restriction ori" = X,
        codeunit "Report Get Msg ori" = X,
        codeunit "Report List Msg ori" = X,
        codeunit "Report Msg Handler ori" = X,
        codeunit "Report Run Exec ori" = X,
        codeunit "Report Run Msg ori" = X,
        codeunit "Report SaveAs Msg ori" = X,
        codeunit "SE Msg Handler ori" = X,
        codeunit "SE Register Msg ori" = X,
        codeunit "SE Restart Msg ori" = X,
        codeunit "SE Run Msg ori" = X,
        codeunit "SE Schedule Msg ori" = X,
        codeunit "Schedule Calc ori" = X,
        codeunit "Scheduler API Client ori" = X,
        codeunit "Scheduler Events ori" = X,
        codeunit "Scheduler Handler ori" = X,
        codeunit "Scheduler Manual Evt ori" = X,
        codeunit "Scheduler Mgt ori" = X,
        codeunit "Scheduler Wizard Reg. ori" = X,
        codeunit "Secrets ori" = X,
        codeunit "Status Get Msg ori" = X,
        codeunit "Status Msg Handler ori" = X,
        codeunit "Status Restart Msg ori" = X,
        codeunit "Status RestartIf Msg ori" = X,
        codeunit "Telegram Msg ori" = X,
        codeunit "Telegram Notif. ori" = X,
        codeunit "Telegram Send ori" = X,
        codeunit "WhoAmI Subscriber ori" = X,
        codeunit "Workspace Preview Msg ori" = X;
}
